### ISSUE TITLE
Consider using proper SQL parser

### ISSUE THREAD

**Issue by nene** [sql-formatter-org/sql-formatter#117]
Currently the formatter is pretty dumb. It's looking for certain keywords and trying to make some formatting guesses based on these. A better approach would be to use an actual parser like https://github.com/taozhi8833998/node-sql-parser

**Comment by osv** [comment]
pretty sure that parser ast tree does not contains info about comments in sql.. but I'm might be wrong.

**Comment by nene** [comment]
You're right. This specific parser completely discards all comments.

Should be possible to modify the parser though to also gather info about comments.

**Comment by romainr** [comment]
It might have caveats: if the parser is validating, it might not work properly on invalid queries or grammar that it does not know (we had issues with that in Hue SQL Editor).

To note that https://github.com/taozhi8833998/node-sql-parser is GPL too.

I was surprised on how well sql-format handle big Hive queries, so the current approach has some good sides. Could be a pluggable option to select which parser to use.

**Comment by nene** [comment]
Closing this. That's a larger topic that's in our minds anyway. No real need for an issue to keep track of it.
