### ISSUE TITLE
Add support for SOQL - Salesforce Object Query Language

### ISSUE THREAD

**Issue by AllanOricil** [sql-formatter-org/sql-formatter#122]
When using the StandardSqlFormatter

Actual Result:
![image](https://user-images.githubusercontent.com/55927613/107882304-6e77b280-6ee0-11eb-97d0-f25d8f1f0def.png)

Expected Result:

![image](https://user-images.githubusercontent.com/55927613/107882329-8818fa00-6ee0-11eb-84ae-03f13f051563.png)

**Comment by AllanOricil** [comment]
To fix my problem I created this small function that I call after calling the formatter. It works for my use case because in the SOQL syntax the characters `-` `+` and `:` are only used for dates.

`````js
export const formatDateTime = (input) => {
  const inputChars = input.split('')
  for (let i = input.length - 1; i > 0; i--) {
    if (['-', ':', '+'].includes(input[i])) {
      inputChars.splice(i - 1, 1)
    }
  }
  return inputChars.join('')
}
````

**Comment by nene** [comment]
Which SQL dielact are you using that supports these date-time literals?

**Comment by AllanOricil** [comment]
@nene it is called SOQL. It is the Salesforce Object Query Language.

**Comment by AllanOricil** [comment]
@nene the standardSQLFormatter works well with SOQL. The only thing I noticed that I could not format well were these date-time literals.

**Comment by AllanOricil** [comment]
You can take a look here on the documentation https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql.htm

It is much more simpler than SQL for other DBs

**Comment by nene** [comment]
Thanks. I'll take a look at supporting this. Can't promise when.

P, 14. veebruar 2021 17:54 Allan Oricil <notifications@github.com> kirjutas:

**Comment by AllanOricil** [comment]
@nene thanks.

**Comment by AllanOricil** [comment]
@nene  I can start the PR and help you. The only thing I could not find how to fix was the date/time literals. I could not find a config in the Tokenizer to avoid separating the date/time numbers

**Comment by nene** [comment]
Well, the thing is, such thing has not been implemented yet :)

**Comment by AllanOricil** [comment]
@nene  this is the regex I'm using to identify Salesforce DateTime formats. Im using it in monaco editor for tokenization (styling tokens)

I tested it with all possible date time formats and it works perfectly.

/[+-]?\d{4}(-[01]\d(-[0-3]\d(T[0-2]\d:[0-5]\d:?([0-5]\d(\.\d+)?)?([+-][0-2]\d:[0-5]\d)?Z?)?)?)?/
