### ISSUE TITLE
Upper case option affect table fields names

### ISSUE THREAD

**Issue by royKarseboom** [sql-formatter-org/sql-formatter#156]
Hi, in the case were the field name is a also a keyword in the language chosen, the field is being capitilized.
for example:
running formatter on the following with `-u  -l postgresql` options:
`CREATE TABLE users(id INT PRIMARY KEY, name TEXT NOT NULL);`
yields:
`CREATE TABLE users(id INT PRIMARY KEY, NAME TEXT NOT NULL);`
as opposed to just leaving it the same way.
tnx!

**Comment by nene** [comment]
The issue here has multiple levels:

1. `NAME` is not a reserved keyword (just a plain keyword) and can therefore be used as an identifier in most contexts. However SQL Formatter currently treats all keywords the same (whether reserved or not).
2. PostgreSQL is particularly complicated:
    > Even reserved key words are not completely reserved in PostgreSQL, but can be used as column labels (for example, `SELECT 55 AS CHECK`, even though `CHECK` is a reserved key word).

**Comment by karlhorky** [comment]
Just ran into this now too, `actors.name` was lowercase before 😲

```sql
CREATE TABLE
  actors (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(80) NOT NULL
  );
```

@nene what are your thoughts on an option `keywordCaseIgnore` which is an array of any-case keywords to ignore when changing the case? Could be useful for multiple things, eg.

```js
const options = {
  language: 'postgresql',
  keywordCase: 'upper',
  keywordCaseIgnore: [
    // Avoid casing name fields in tables
    'name',
    // Avoid casing data types
    'varchar',
    'integer',
    // ...
  ],
}
```

**Comment by karlhorky** [comment]
I also just saw the following PR by @chrjorgensen for a new option `identifierCase: 'preserve' | 'upper' | 'lower'`, which was also released in [`sql-formatter@14.0.0`](https://github.com/sql-formatter-org/sql-formatter/releases/tag/v14.0.0)

- https://github.com/sql-formatter-org/sql-formatter/pull/663

**Comment by nene** [comment]
@karlhorky I'd rather not add a separate way of tweaking which keywords get capitalized. There already exists a way to create a custom dialect. One can simply extend an existing dialect and change the list of keywords. See docs for the "dialect" option.

**Comment by karlhorky** [comment]
> There already exists a way to create a custom dialect. One can simply extend an existing dialect and change the list of keywords. See docs for the "dialect" option.

Interesting! Maybe our organization can create a custom PostgreSQL dialect that will work for most cases... 🤔

I guess I would still like to be able to have lowercase data types, but maybe the combination [`dataTypeCase` - #653](dataTypeCase) and dialects would cover all cases we're currently interested in.

**Comment by karlhorky** [comment]
Opened a draft PR for experimental `datatypeCase` option, still need to add the main functionality and tests:

- https://github.com/sql-formatter-org/sql-formatter/pull/673

I'm basing it off the `identifierCase` PR:

- https://github.com/sql-formatter-org/sql-formatter/pull/663

**Comment by karlhorky** [comment]
## Custom Dialect solution

> Maybe our organization can create a custom PostgreSQL dialect that will work for most cases... 🤔

Using [the `dialect` option with a custom dialect (experimental)](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/dialect.md#custom-dialect-configuration-experimental) I made a modified PostgreSQL dialect with the `'NAME'` keyword excluded:

```ts
import { formatDialect, postgresql } from 'sql-formatter';

const postgresWithoutNameKeyword = {
  ...postgresql,
  tokenizerOptions: {
    ...postgresql.tokenizerOptions,
    reservedKeywords: postgresql.tokenizerOptions.reservedKeywords.filter(
      (reservedKeyword) => reservedKeyword !== 'NAME',
    ),
  },
};

formatDialect('cReAtE tAbLe actors ( name VARCHAR(80) NOT NULL )', {
  dialect: postgresWithoutNameKeyword,
  keywordCase: 'upper'
});

/*
  CREATE TABLE
    actors (
      name VARCHAR(80) NOT NULL
    )
*/
```

The `name` identifier stays lowercase 🎉

**Comment by nene** [comment]
I did a sort-of basic fix for this, removing the following from list of keywords:

- label
- location
- name
- names
- release
- type
- types

There are quite a bit of other keywords in this list that we probably should drop, but at least for start the most problematic ones should be gone now.

**Comment by karlhorky** [comment]
Oh nice, that's great!

I'll remove my custom dialect once https://github.com/sql-formatter-org/sql-formatter/commit/d34557bc97fd2f6be3ad8131a99ec45da296da22 is published in a release 🙌
