### ISSUE TITLE
Group Keywords into relevant Reserved Statements instead of every individual word

### ISSUE THREAD

**Issue by inferrinizzard** [sql-formatter-org/sql-formatter#226]
\<Transferred from inferrinizzard/prettier-sql#18\>

**Describe the Feature**
For some keywords, they are only ever used as part of a larger statement that should be formatted as one piece
(ie. - Spark: ITEMS is only in HIVE COLLECTION ITEMS, TERMINATED is only in TERMINATED BY, etc.)

There may not be an easy of doing this besides hand checking every keyword

**Comment by nene** [comment]
That's surely something to be done, though it's a really large task which essentially requires deeply analyzing the syntax of all supported dialects.

That is to say, there's no clear completion criteria for this task.

It's also implementation specific. It might become irrelevant when we reorganize our parsing logic.

Finally it's not a problem that we'd easily forget about. Just open one of the `*.formatter.ts` files and you're immediately reminded of the issue.

Therefore I'd vote to close this issue.
