### ISSUE TITLE
Feature Request: Make it as plugin for prettier

### ISSUE THREAD

**Issue by inferrinizzard** [sql-formatter-org/sql-formatter#228]
\<Transferred from inferrinizzard/prettier-sql#74\>

**Describe the Feature**

- Create a prettier plug-in [`@prettier/plugin-sql`](https://prettier.io/docs/en/plugins.html)
- Optional: remove standalone VSCode plugin - it's simpler to avoid maintenance and focus on functionality within Prettier

**Why do you want this feature?**

Firstly, thank you for your great work! This formatter has much more usable settings than [prettier-plugin-pg](https://github.com/benjie/prettier-plugin-pg) with [sql-formatter](https://github.com/zeroturnaround/sql-formatter) that misses even basic settings like line width.

However, there're some good features of [prettier](https://github.com/prettier/prettier):
- lint/format all files in project
- project based config and ignore files (also respected by [VSCode prettier plug-in](https://github.com/prettier/prettier-vscode)) that can be committed to repository and shared across team, this was already requested in inferrinizzard/prettier-sql#61 

Rather than implement and maintain that, it's imo simpler to publish a prettier plug-in and have benefits not only of the functionality, but also larger adoption in prettier [community](https://prettier.io/docs/en/plugins.html#community-plugins)

**Info**

- How would you be calling / using the script? 
  - `prettier` from command line
  - existing lint/format scripts in `package.json` using `prettier`
  - [VSCode prettier plug-in](https://github.com/prettier/prettier-vscode)
- What SQL language(s) does this apply to?  `any`
- What Node version? (If applicable) `n/a`

**Comment by gaving** [comment]
There seems to be https://github.com/rx-ts/prettier/tree/master/packages/sql these days... 👀

**Comment by nene** [comment]
Cool! Thanks for sharing.

**Comment by nene** [comment]
Closing this, as an external plugin currently already exists.
