### ISSUE TITLE
[FORMATTING] Space is inserted before bracket for Map keys with . and -

### ISSUE THREAD

**Issue by inferrinizzard** [sql-formatter-org/sql-formatter#230]
\<Transferred from inferrinizzard/prettier-sql#85\>

**Describe the bug**
When formatting code with MAP keys that have `.` in them, the formatter adds a space between map name and index.

**Expected Output**
```
SELECT
    id,
    measures_map['bucket.lower'] AS bucket_lower,
    SUM(1) as cnt
FROM some.table
GROUP BY
    id,
    measures_map['bucket.lower']
```

**Actual Output**
```
SELECT
    id,
    measures_map ['bucket.lower'] AS bucket_lower,
    SUM(1) as cnt
FROM some.table
GROUP BY
   id,
   measures_map ['bucket_lower']
```

Note: if I cared about measures_map['somekey'] the formatter behaves perfectly as expected. I have not done an exhaustive search, but I see that `_` are treated correctly, but `.` and `-` are not.

**Usage**

- How are you calling / using the script? (Please provide a code snippet, if applicable)
I've tried through using `Format Document` and `Format on Save`

- What SQL language(s) does this apply to?
I'm writing in Presto/Trino and have tried `sql`, `bigquery`, `spark`, and `hive` and get the same results

- What Node version? (If applicable)
v17.9.0

**Comment by nene** [comment]
Relates to #219 where I just deleted this feature completely as the implementation was one big hack. Wasn't aware of this bug, which shows I was on the right track to delete the code.

Will be reimplement the feature it in a more reliable fashion.
