### ISSUE TITLE
[FORMATTING] Should Preserve the Space between OR and REPLACE SQL Keywords

### ISSUE THREAD

**Issue by inferrinizzard** [sql-formatter-org/sql-formatter#231]
\<Transferred from inferrinizzard/prettier-sql#87, related to #226\>

**Describe the bug**
It removes the space between OR and REPLACE.  in other words it converts OR REPLACE to ORREPLACE

**To Reproduce**

Try to format something like this one.
CREATE OR REPLACE FUNCTION "public" . "set_current_timestamp_updated_at"() RETURNS TRIGGER AS $$

**Expected behavior**
It should preserve the space between the OR and REPLACE Keywords. which should remain two words. 

**Screenshots**

![Peek 2022-05-17 07-09](https://user-images.githubusercontent.com/26034746/168710372-1cc022d1-1ade-487a-bc25-699fa6bbce2b.gif)

**Usage**

- Occurred with PostgreSQL, Not sure about other SQL standards
- VSCode version? Version 1.66.2
- What are your currently configured VSCode settings for the `prettier-sql` extension, if relevant to the issue?

// following setting is under the settings.json file. but no entry with the key "prettier-sql"
"[plsql]": {
        "editor.defaultFormatter": "inferrinizzard.prettier-sql-vscode"
},

**Additional context**
Pl. comment if you need anything specific to hunt this bug.

**Comment by nene** [comment]
Unable to reproduce. Tried with both 5.x and 6.x. Even tried with VSCode plugin.

@inferrinizzard Do you know anything about this.
