### ISSUE TITLE
[FORMATTING] Formatter adds another level of indentation in sub-query

### ISSUE THREAD

**Issue by m-ahmadkhan** [sql-formatter-org/sql-formatter#244]
**Input data**
It adds another level of indentation in the subquery. For example, if we format the following query:

```sql
SELECT mycol, mycol2, mycol3 FROM (
    SELECT mycol, mycol2, mycol3 FROM `my_dataset.my_table`
)
WHERE mycol != 1002 AND (
    mycol2 = "something" OR mycol3 = "something2"
);
```

With the config:

```json
{
  "language": "bigquery",
  "tabWidth": 2,
  "useTabs": false,
  "keywordCase": "upper",
  "indentStyle": "standard",
  "multilineLists": 4,
  "logicalOperatorNewline": "before",
  "aliasAs": "always",
  "tabulateAlias": false,
  "commaPosition": "after",
  "newlineBeforeOpenParen": false,
  "newlineBeforeCloseParen": true,
  "expressionWidth": 50,
  "linesBetweenQueries": 2,
  "denseOperators": false,
  "newlineBeforeSemicolon": false
}
```

**Actual Output**

It generates the following query (notice 2 tabs in the sub-query `SELECT mycol, mycol2 ...`). The indentation in the `AND` block is correct, as the ending parenthesis matches with the starting indent of `AND`, but the ending parenthesis in the `FROM` block doesn't match the indent of `FROM`.

```sql
SELECT mycol, mycol2, mycol3
FROM (
    SELECT mycol, mycol2, mycol3
    FROM `my_dataset.my_table`
  )
WHERE
  mycol != 1002
  AND (
    mycol2 = "something"
    OR mycol3 = "something2"
  );
```

**Expected Output**
It should have produced the following query:

```sql
SELECT mycol, mycol2, mycol3
FROM (
  SELECT mycol, mycol2, mycol3
  FROM `my_dataset.my_table`
)
WHERE
  mycol != 1002
  AND (
    mycol2 = "something"
    OR mycol3 = "something2"
  );
```

**Usage**

SQL formatter version: 7.0.1

SQL language: used it for bigquery

Installed `sql-formatter` using yarn, and formatting the files using:

```
yarn sql-formatter -o hello.sql -c config.json hello.sql
```

**Comment by nene** [comment]
Closing this as `multilineLists`, `newlineBeforeOpenParen` and `newlineBeforeCloseParen` options are now deprecated and will be dropped in next major version.
