### ISSUE TITLE
[FORMATTING] Issues with create view and joins - bigquery

### ISSUE THREAD

**Issue by m-ahmadkhan** [sql-formatter-org/sql-formatter#267]
**Input data**
```sql
create or replace view `my_dataset.my_view` as (
  select t1.col1, t1.col2 from `my_dataset.my_table` as t1
  inner join `my_dataset.my_other_table` as t2 on t1.col1 = t2.col3 and t1.col2 = t2.col4
  where t1.col3 = "my_val" and t1.col4 = "my_val2"
);
```

Config used:
```json
{
  "language": "bigquery",
  "tabWidth": 2,
  "useTabs": false,
  "keywordCase": "upper",
  "indentStyle": "standard",
  "multilineLists": "always",
  "logicalOperatorNewline": "before",
  "aliasAs": "always",
  "tabulateAlias": false,
  "commaPosition": "after",
  "newlineBeforeOpenParen": false,
  "newlineBeforeCloseParen": true,
  "expressionWidth": 50,
  "linesBetweenQueries": 2,
  "denseOperators": false,
  "newlineBeforeSemicolon": false
}
```

**Expected Output**

```sql
CREATE OR REPLACE VIEW `my_dataset.my_view` AS (
  SELECT
    t1.col1,
    t1.col2
  FROM
    `my_dataset.my_table` AS t1
  INNER JOIN
    `my_dataset.my_other_table` AS t2
  ON
    t1.col1 = t2.col3
    AND t1.col2 = t2.col4
  WHERE
    t1.col3 = "my_val"
    AND t1.col4 = "my_val2"
);
```

**Actual Output**

```sql
create
OR REPLACE view `my_dataset.my_view` AS (
  SELECT
    t1.col1,
    t1.col2
  FROM
    `my_dataset.my_table` AS t1
    INNER JOIN `my_dataset.my_other_table` AS t2 ON t1.col1 = t2.col3
    AND t1.col2 = t2.col4
  WHERE
    t1.col3 = "my_val"
    AND t1.col4 = "my_val2"
);
```

There are a few issues with this output:

1. CREATE OR REPLACE VIEW:
   - It didn't convert `create` and `view` to uppercase, despite having the config `keywordCase` set to `upper`
   - `OR` in `CREATE OR REPLACE VIEW` should not be considered a logical operator, and be kept in a single line
2. INNER JOIN:
   - INNER JOIN keyword should have one less indent level
   - Table name for the join should go to a separate line (just like it handles the FROM clause)
   - ON should go to a separate line as well
   - The join condition after ON should go to a separate line (just like it handles the WHERE clause)

**Usage**

- How are you calling / using the library?

Installed sql-formatter using yarn, and formatting the files using:

```bash
yarn sql-formatter -o hello.sql -c config.json hello.sql
```

- SQL language: bigquery
- SQL formatter version: 7.0.2

**Comment by nene** [comment]
Thanks for the report.

The formatting of `OR` and `AND` is currently troublesome. It works well inside the `WHERE` clause, but produces bad outcomes pretty much everywhere else. A known issue. Planning to improve.

> - INNER JOIN keyword should have one less indent level
> - Table name for the join should go to a separate line (just like it handles the FROM clause)
> - ON should go to a separate line as well
> - The join condition after ON should go to a separate line (just like it handles the WHERE clause)

The formatting of `INNER JOIN` works as designed. That is, joins are nested inside a FROM block.

That's of course a matter of personal preference. I've noted that indenting joins on the same level as FROM is fairly common practice. The formatter actually even does this when switched to `indentStyle: "tabularLeft"` format. It would probably be good to make this configurable.

**Comment by nene** [comment]
The formatting of `CREATE VIEW` and joins has now been reviewed and corrected for all SQL dialects.
