### ISSUE TITLE
[VSCODE] Extension has links to the old repository

### ISSUE THREAD

**Issue by neoGeneva** [sql-formatter-org/sql-formatter#286]
The vscode extension references the old repo. 

Personally I was confused that the extension had updated, and when I clicked through to the repo to see what changes there was that there had been no commits in months, and kinda assumed the worst and it was a malicious update.

**Comment by inferrinizzard** [comment]
Ah forgot to update package metadata, will publish new patch shortly

**Comment by neoGeneva** [comment]
Awesome, thank you!

**Comment by inferrinizzard** [comment]
Resolved in v1.1.1 #287
