### ISSUE TITLE
[VSCODE] Prettier-SQL.tabSizeOverride not working

### ISSUE THREAD

**Issue by enigmazack** [sql-formatter-org/sql-formatter#289]
**Describe the bug**
I want to use a tab width with 4, but I can't find the proper settings

**To Reproduce**
check Prettier-SQL: Ignore Tab Settings
setting Prettier-SQL.tabSizeOverride to 4

1. Check Prettier-SQL: Ignore Tab Settings
2. Setting Prettier-SQL.tabSizeOverride to 4
3. Format with Shift + Alt + F
4. No matter how I change the settings, always format the file with tab width of 2

**Comment by Anutrix** [comment]
Facing same issue. Is there any update on this?

**Comment by ricardobarreira** [comment]
Same issue here.

**Comment by nene** [comment]
The fix should now be released in 1.4.0 version of the VSCode plugin.
