### ISSUE TITLE
[FORMATTING] Formatter breaks SQL for BigQuery user-defined functions

### ISSUE THREAD

**Issue by m-ahmadkhan** [sql-formatter-org/sql-formatter#309]
**Input data**

Bigquery documentation on UDFs: https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions

```sql
CREATE OR REPLACE FUNCTION
  fn.GET_ID(path STRING, idx INT64)
  RETURNS INT64 AS (
    SAFE_CAST(SPLIT(path, ',') [OFFSET (idx)] AS INT64)
  );
```

**Expected Output**
It should leave it pretty much as it is.

**Actual Output**

```sql
CREATE
OR REPLACE FUNCTION fn.GET_ID(path STRING, idx INT64) AS RETURNS INT64 AS (SAFE_CAST(SPLIT(path, ',') [OFFSET (idx)] AS INT64));
```

There are a few issues with the output:

- It makes it pretty hard to read by moving everything in a single line. The original input looks perfect to me.
- Major concern is that it is adding the `AS` keyword before `RETURNS`, which breaks the SQL.

**Usage**

- How are you calling / using the library?
   - `yarn sql-formatter -o abc.sql -l bigquery -c config.json abc.sql`
- What SQL language(s) does this apply to?
   - bigquery
- Which SQL Formatter version are you using? 
   - v8.1.0

**Comment by nene** [comment]
Fixed by #319
