### ISSUE TITLE
[VSCODE] PostgreSQL string concatenation operator || breaks code 

### ISSUE THREAD

**Issue by jldevezas** [sql-formatter-org/sql-formatter#313]
**Input data**

```sql
SELECT col1 || '::' || col2;
```

**Expected Output**

No spaces between '|' characters.

```sql
SELECT
  col1 || '::' || col2;
```

**Actual Output**

Spaces added between '|' characters.

```sql
SELECT
  col1 | | '::' | | col2;
```

**Usage**

- Using through Visual Studio Code extension: Prettier SQL VSCode v1.1.1
- PostgreSQL 12/14 (PL/pgSQL)

**Comment by jldevezas** [comment]
Here's another easy one. Let's make this the best SQL formatting extension for vscode! :-)

**Comment by nene** [comment]
That's an issue with VSCode extension. Duplicate of #227 

SQL Formatter itself handles it just fine.
