### ISSUE TITLE
[FORMATTING] Formatting add space between : and value

### ISSUE THREAD

**Issue by sylvainmouquet** [sql-formatter-org/sql-formatter#323]
**Input data**
```sql
-- name: create-activity<!
INSERT INTO
  activities (stack_identifier, action, ldap, created_at)
VALUES
  (:stack_identifier, :action, :ldap, now())
RETURNING
  id;
```

**Expected Output**

```sql
-- name: create-activity<!
INSERT INTO
  activities (stack_identifier, action, ldap, created_at)
VALUES
  (:stack_identifier, :action, :ldap, now())
RETURNING
  id;

```

**Actual Output**

```sql
-- name: create-activity<!
INSERT INTO
  activities (stack_identifier, action, ldap, created_at)
VALUES
  (: stack_identifier,: action,: ldap, now())
RETURNING
  id;

```

**Usage**

- How are you calling / using the library?
With the command line
- What SQL language(s) does this apply to?
postgresql
- Which SQL Formatter version are you using?
`8.2.0 `

node version
`v16.16.0`

environment : ubuntu wsl in windows 10

**Comment by nene** [comment]
Hmm... I think this depends on the driver used for connecting to database. Googling around I also see `?` being used with JDBC driver: https://jdbc.postgresql.org/documentation/head/server-prepare.html

But so far haven't found an example of `:name` syntax.

**Comment by sylvainmouquet** [comment]
It's a template of sql used by aiosql to separate Python code to sql queries and manage params. In MacOS the formatting was ok with sql formatter but when i try with Windows/wsl the formating is not the same.

**Comment by nene** [comment]
It's very unlikely that the formatter works differently in different operating systems. Are you sure you used the same version and same settings? You can also compare it with the [web version](https://sql-formatter-org.github.io/sql-formatter/).

Currently the `:name` syntax works for `language: db2 | plsql | tsql`, as documented in our [parameters syntax docs](https://github.com/sql-formatter-org/sql-formatter/blob/master/sql/parameters.md).

**Comment by sylvainmouquet** [comment]
the output result is not the same between the version 6.1.5 and the version 7.0.4
I stay with the version 6
You can close the issue

**Comment by nene** [comment]
Hmm... that feels sad :(

The [7.0.0 release](https://github.com/sql-formatter-org/sql-formatter/releases/tag/v7.0.0) indeed dropped support for `:name` syntax for parameter placeholders as part of a general cleanup of the support of parameter placeholders across many languages. This was done based on the official docs of each SQL dialect.

It seems though that this placeholder syntax very much depends on additional database-connection tools used. Perhaps this needs to be made configurable. Not sure. It definitely needs more research.
