### ISSUE TITLE
Feature request: Don't format an SQL query

### ISSUE THREAD

**Issue by m-ahmadkhan** [sql-formatter-org/sql-formatter#330]
**Describe the Feature**
Use-case: someone integrates sql-formatter to format the .sql files in their project, but the formatter breaks their SQL due to a bug. They won't be left with any other option than to disable the formatter for their project.

Solution 1 (won't work): Similar to [.prettierignore file](https://prettier.io/docs/en/ignore.html), we should introduce a file `.sqlformatterignore` (or a better name), and the formatter wouldn't format the sql files in the directories/files listed in the ignore file. Now, they can list all the .sql files on which the formatter doesn't work in that file until we fix the bug for them.

Solution 2: We can support a `-- @no-format` (or a better name) comment (just like `// @ts-ignore`) at the start of the file, and if found, the formatter will return the query as is.

**Comment by nene** [comment]
I think that's not really much better either. It raises the same question: if you don't want sql-formatter to format a file, why do you pass that file as an argument?

Additionally, you are proposing a problem here, and then proposing a solution for that hypothetical problem. We don't really know if somebody actually has such a problem.

**Comment by m-ahmadkhan** [comment]
And we can find such examples from almost all tools that help with development.

ESLint: `@eslint-disable-next-line` comment, and `.eslintignore` file
Prettier: `.prettierignore` file
Typescript: `@ts-ignore` and `@ts-nocheck` comments

**Comment by nene** [comment]
Nice to hear of some real-world usage.

I'm still thinking though whether this could be better handled by external
tooling. For example there's a [prettier plugin](
https://github.com/un-ts/prettier/tree/master/packages/sql). With that, it
would be possible to use standard .prettierignore file without introducing
yet another ignore file/setting to the world.

An in-file comment (like @ts-ignore) is mostly used to disable some line or
block of code, not an entire file. Disabling formatting for a part of file
would currently require a major change in the formatter, so I'd rather not
go there for now.

**Comment by nene** [comment]
The problems described here can be accomplished with external tooling.

I'm closing this as out of scope to prioritize other features that can't be implemented outside of the formatter.
