### ISSUE TITLE
Double quotes (") in SQL fails formatting for Spark dialect

### ISSUE THREAD

**Issue by 5takes** [sql-formatter-org/sql-formatter#331]
Using this module in SQL formatter in VSCode plug-in. However if a double-quote is found, the tokenizer errors Tokenizer.tokenize call with the following error
`Error: Parse error: Unexpected ""`

Formatter works when double quotes are replaced with single quotes.

**Comment by inferrinizzard** [comment]
Looks like the string specification for Spark is wrong, will update soon

**Comment by nene** [comment]
Fix now released in 9.0.0-beta4.
