### ISSUE TITLE
Feature request: Blank lines between CTEs

### ISSUE THREAD

**Issue by ingo-m** [sql-formatter-org/sql-formatter#345]
**Describe the Feature**

Currently, Common Table Expressions (CTEs) are not recognized as separate statements, and are not separated by blank lines (irrespective of the `Prettier-SQL.linesBetweenQueries` setting).

Example (auto-formatted with the VSCode extension):
```
WITH
  example_cte_1 AS (
    SELECT
      a
    FROM
      b
    WHERE
      c = 1
  ),
  example_cte_2 AS (
    SELECT
      c
    FROM
      d
    WHERE
      e = 2
  ),
  final AS (
    SELECT
      *
    FROM
      example_cte_1
      LEFT JOIN example_cte_2 ON b = d
  )
SELECT
  *
FROM
  final;
```

It would be great if the CTEs could be separated like so (with blank lines between separate CTEs, and no indentation due to `WITH`):
```
WITH

example_cte_1 AS (
  SELECT
    a
  FROM
    b
  WHERE
    c = 1
),

example_cte_2 AS (
  SELECT
    d
  FROM
    e
  WHERE
    f = 2
),

final AS (
  SELECT
    *
  FROM
    example_cte_1
    LEFT JOIN example_cte_2 ON a = d
)

SELECT
    *
FROM
  final;
```

**Why do you want this feature?**

CTEs are useful for structuring complex queries, and are commonly separated by blank lines for better readability.

**Comment by nene** [comment]
Thanks for the suggestion.

This style of formatting doesn't currently align with how the SQL Formatter formats all other parts of an SQL statement. No blank lines are left anywhere within a statement.

As you note, CTE-s aren't recognized as separate statements, and indeed according to SQL grammar they don't constitute separate statements. Statements in SQL are separated by `;`. The name of `linesBetweenQueries` setting is somewhat misleading. It really would be better named `linesBetweenStatements` (this also relates to #329 - another thing to enhance about this config option).

I do see the merit in this proposal, but this style likely wouldn't be the default. For now though, our main goal is to improve the formatter in general and avoid adding more configuration options. Something to keep in mind for the future.

**Comment by ingo-m** [comment]
@nene thanks for the explanation.

I will close this.

PS: If you decide to support CTEs in the future I think that would make your tool very interesting for people working with dbt on ELT processes, where CTEs are used heavily (e.g. https://docs.getdbt.com/terms/cte#cte-example - in practice often much longer than this example). I am not aware of any easy to use auto-formatter for that context. sqlfluff tries to address that use case, but in my experience it's just not working (it tries to be a very complex, advanced linter, but it's not possible to just use it as an auto-formatter).
