### ISSUE TITLE
Feature Request: Colorize 

### ISSUE THREAD

**Issue by wirekang** [sql-formatter-org/sql-formatter#349]
**Describe the Feature**
It would be great if `sql-formatter` has option for colorize result using **https://github.com/chalk/chalk** or something.

**Comment by nene** [comment]
Thanks for the suggestion. However, this is out of scope for this library that focuses on formatting.

If you want syntax highlighting in terminal, you're better off using terminal-based editors like Vim.

**Comment by Farnsi** [comment]
Highlight with https://www.npmjs.com/package/sql-highlight
