### ISSUE TITLE
[FORMATTING] formatter doesn't format multiword commands correctly with keywordCase = "upper"

### ISSUE THREAD

**Issue by m-ahmadkhan** [sql-formatter-org/sql-formatter#356]
**Input data**
```sql
CREATE
OR
REPLACE
TABLE
FUNCTION
  `mydataset.mytablefunc` (p1 STRING, p2 STRING) AS (
    SELECT *
    FROM
      mtytable2
    WHERE
      col1 = p1 AND col2 = p2
  );
```

**Actual Output**

Formatting it with the following config:

```
{
  "language": "bigquery",
  "keywordCase": "upper"
}
```

produces the following result:
```sql
CREATE
OR
REPLACE
TABLE
FUNCTION
  `mydataset.mytablefunc` (p1 STRING, p2 STRING) AS (
    SELECT
      *
    FROM
      mtytable2
    WHERE
      col1 = p1
      AND col2 = p2
  );
```

Bug: It didn't format `CREATE OR REPLACE TABLE FUNCTION` to a single line.

And if I format the same query with keywordCase: "preserve", it formats the query as expected.

```
{
  "language": "bigquery",
  "keywordCase": "preserve"
}
```

Output:

```sql
CREATE OR REPLACE TABLE FUNCTION
  `mydataset.mytablefunc` (p1 STRING, p2 STRING) AS (
    SELECT
      *
    FROM
      mtytable2
    WHERE
      col1 = p1
      AND col2 = p2
  );
```

**Usage**

- How are you calling / using the library? `yarn sql-formatter -o query.sql -l bigquery -c config.json query.sql`
- What SQL language(s) does this apply to? `bigquery`
- Which SQL Formatter version are you using? `9.0.0-beta4`

**Comment by nene** [comment]
Fix for this is now released in 9.0.0-beta.5
