### ISSUE TITLE
[FORMATTING] # prefixed temporary tables are not formatted correctly

### ISSUE THREAD

**Issue by AlexAVL** [sql-formatter-org/sql-formatter#358]
**Input data**
Which SQL and options did you provide as input?

Using both the SQL formatter and Redshift formatter, a space is added between a `#` prefix and a table name. Redshift allows table names beginning with `#` to denote a temporary table, without the use of the `TEMP` keyword: https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html

The result is a statement which Redshift cannot parse.

**Input**

```sql
CREATE TABLE #tablename AS ...;
```

**Expected Output**

```sql
CREATE TABLE #tablename AS ...;
```

**Actual Output**

```sql
CREATE TABLE # tablename AS ...;
```

**Usage**

- How are you calling / using the library? NodeJS, but I have noticed it in the VSCode extension too
- What SQL language(s) does this apply to? Redshift at minimum.
- Which SQL Formatter version are you using? Redshift

**Comment by nene** [comment]
Fix for this is now released in 9.0.0-beta.6
