### ISSUE TITLE
[FORMATTING] [TSQL] Wrong indentation for "IF" keyword 

### ISSUE THREAD

**Issue by leo-buneev** [sql-formatter-org/sql-formatter#361]
**Input data**
default settings, language = tsql

**Expected Output**

```sql
SELECT
  1

IF EXISTS (
  SELECT
    1
  )
DROP TABLE
  #temp
```

**Actual Output**

```sql
SELECT
  1 IF EXISTS (
    SELECT
      1
    )
DROP TABLE
  #temp
```

Formatter considers "IF EXISTS" to be a part of "SELECT", while that's not the case in TSQL - "IF" can't be part of statement, so in fact it starts new statement. (https://docs.microsoft.com/en-us/sql/t-sql/language-elements/if-else-transact-sql?view=sql-server-ver16, https://stackoverflow.com/questions/63447/how-do-i-perform-an-if-then-in-an-sql-select)

**Usage**

- How are you calling / using the library?
Formatting my company's SQL code by using ESLint plugin, that uses sql-formatter as a library.

- What SQL language(s) does this apply to?
TSQL definitely, others not sure

- Which SQL Formatter version are you using?
8.2.0

I've tried to create PR for it, but not sure how control-of-flow keywords should be handled properly. If I add `IF` in `reservedCommands` in `tsql.formatter.ts`, then in example above `IF` indentation is correct but `EXISTS` gets pushed to the next line, which is probably not desirable.

**Comment by nene** [comment]
Unfortunately there's currently no support for any kind of procedural SQL. Support for this is not really even planned, as there are too many big problems to solve with formatting of the regular SQL.

**Comment by leo-buneev** [comment]
Got you, that's reasonable.

Just in case - would you accept PR contributing support for basic procedural TSQL?

**Comment by nene** [comment]
Sure. Open for PR-s.
