### ISSUE TITLE
Unexpected token error after using into React 

### ISSUE THREAD

**Issue by dhavalthumar37** [sql-formatter-org/sql-formatter#368]
![image](https://user-images.githubusercontent.com/10174524/182386492-182655a6-cc48-4662-a809-f777f30fdad2.png)
In existing React application I have installed sql-formatter via npm and added  {format('SELECT * FROM tbl')} in render method of component. On build getting above error, what cloud be the root cause of this ?

**Version:** 
 "react": "16.11.0",
"react-dom": "16.11.0",

**Comment by nene** [comment]
I doubt it's related to React. Rather there might be a problem with TypeScipt. Which version of TypeScript are you using?

**Comment by dhavalthumar37** [comment]
3.6.4

**Comment by dhavalthumar37** [comment]
Thanks.
After updating version of typescript, it working as expected.

**Comment by nene** [comment]
Nice to hear :)

Posting my already-written comment here in case somebody else stumbles on this issue:

3.6 is quite old version of TypeScript (released in 2019). The `import type {...} from ...` syntax was added in [3.8][]. SQL Formatter requires at least [4.5][] as it also uses the `import {type Foo} from ...` syntax.

We're definitely not going to support TypeScript < 4. We might consider supporting older 4.x releases, but so far everyone has solved similar issues by simply upgrading TypeScript :)

[3.8]: https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/
[4.5]: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names
