### ISSUE TITLE
Guide on how to setup a VSCode development environment that allows you to debug tests.

### ISSUE THREAD

**Issue by mgiannakopoulos** [sql-formatter-org/sql-formatter#378]
Hello all, I would like to contribute syntax for a new database database (SingleStoreDB). Being new with typescript and javascript in general, I would like to know what is the ideal way to configure VSCode so as to debug some of the tests.

**Comment by nene** [comment]
Perhaps you could provide more details about which tests do you have trouble with.

I personally only use a few additional VSCode extensions for developing this project: ESLint, EditorConfig for VS Code, Git Blame. And these aren't really related to tests.

**Comment by nene** [comment]
Sorry, I'm closing this.
