### ISSUE TITLE
Custom Formatter

### ISSUE THREAD

**Issue by br0nstein** [sql-formatter-org/sql-formatter#380]
I am wondering if the maintainers would be open to a PR to allow programatic usage to provide a custom Formatter object, rather than only specifying a language flavor that ships with sqlformatter.

The motivation is to allow users with their own SQL flavors that vary in adoption to use this library without modification to format their own SQL. It would allow them to customize how their language spec is defined - for example, so they can codegen the list of commands rather than hardcode them, to minimize the maintenance burden and risk of regression as they add new supported commands or modify the syntax.

Thanks for considering.

**Comment by nene** [comment]
Hi. I'm happy to report that we're open for such a pull request :)

Please see issue #306.

**Comment by nene** [comment]
Closing this as duplicate.
