### ISSUE TITLE
[FORMATTING] plsql create database

### ISSUE THREAD

**Issue by DuShuYuan** [sql-formatter-org/sql-formatter#382]
**Input data**
create database link HSDblink1 connect to SBD_CXTJ identified by huawei123 using '(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = 192.168.111111)(PORT = 1111)))(CONNECT_DATA =(SERVICE_NAME = search)))';

**Expected Output**

```sql

```

**Actual Output**

```sql
create database link HSDblink1 connect to SBD_CXTJ identified by huawei123 using '(DESCRIPTION =(ADDRESS_LIST =(ADDRESS =(PROTOCOL = TCP)(HOST = 192.168.111111)(PORT = 1111)))(CONNECT_DATA =(SERVICE_NAME = search)))';
```

**Comment by nene** [comment]
Well. Seems to be working as expected.

I think you have mistaken "expected output" with the output that the formatter currently produces and you're not happy with.

**Comment by DuShuYuan** [comment]
The content has been modified, but I don't know what the expected value should look like

**Comment by nene** [comment]
Well, I don't really know either. There are many more SQL statements (in PL/SQL and other dialects) that the formatter doesn't handle well.

Currently our main priority is to improve the formatting of the more common SQL syntax, like SELECT, UPDATE, INSERT, DELETE, CREATE TABLE. Plus ensuring that the formatter doesn't break the SQL it receives. Everything else is more in the nice-to-have territory.
