### ISSUE TITLE
Feature Request: Extension for Azure Data Studio

### ISSUE THREAD

**Issue by 1nfected** [sql-formatter-org/sql-formatter#385]
Would it be possible to create an extension for [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio) too?

I really like how this formatter is shaping up and have been using it regularly.
But we do not use vs code when working with sql queries. So now we have to paste our queries in vs code, format it and then bring that back to Azure Data Studio.

**Comment by nene** [comment]
Well... I have nothing against such an extension, but until now I haven't even heard about Azure Data Studio, let alone use it or know how one would write extensions for it.

I think you, as an actual user of this, are in a better position to write such an extension. Feel free to do so.

FYI, you can also use SQL Formatter from command line, or from [the demo website](https://sql-formatter-org.github.io/sql-formatter/), so you don't have to open VSCode for it.

**Comment by 1nfected** [comment]
Yup, I think I'll give this a shot!
