### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by gkssjovi** [sql-formatter-org/sql-formatter#396]
I cannot complie the code with my typescript version.

<img width="784" alt="Screenshot 2022-08-16 at 20 38 23" src="https://user-images.githubusercontent.com/5613459/184943846-d7c97a43-35fb-4456-9de1-dd4a2192a9c0.png">

If there is a problem if you import  the type like this:
`import type { ParamItems } from './formatter/Params';`
instead of this:
`import { type ParamItems } from './formatter/Params';`

YOUR TYPESCRIPT VERSION: 4.3.5

**Comment by inferrinizzard** [comment]
Your typescript version is outdated, please use version >= 4.5

**Comment by gkssjovi** [comment]
Thank you for the reply.
I have downgraded the sql-formatter version and now it's working fine.
