### ISSUE TITLE
[FORMATTING] Declaring statement should not insert space between the '@' symbol and 'temp' text.

### ISSUE THREAD

**Issue by EvenC-tw** [sql-formatter-org/sql-formatter#402]
**Input data**
Which SQL and options did you provide as input?

DECLARE @temp TABLE(id INT)
   INSERT INTO @temp
   SELECT MusicianId
     FROM MusicianInfo
    WHERE MusicianInfoId IN (6990, 5827, 4424, 6809)
   SELECT *
     FROM @temp

- options
  "Prettier-SQL.keywordCase": "upper",
  "Prettier-SQL.commaPosition": "before",
  "Prettier-SQL.linesBetweenQueries": 3,
  "Prettier-SQL.indentStyle": "tabularRight"

**Expected Output**

```sql
DECLARE @temp TABLE(id INT)
   INSERT INTO @temp
   SELECT MusicianId
     FROM MusicianInfo
    WHERE MusicianInfoId IN (6990, 5827, 4424, 6809)
   SELECT *
     FROM @temp
```

**Actual Output**

```sql
DECLARE @ temp TABLE(id INT)
   INSERT INTO @ temp
   SELECT MusicianId
     FROM MusicianInfo
    WHERE MusicianInfoId IN (6990, 5827, 4424, 6809)
   SELECT *
     FROM @ temp
```

**Question**
Declaring statement should not insert space between the '@' symbol and 'temp' text.

**Usage**

- How are you calling / using the library?
vscode
- What SQL language(s) does this apply to?
T-SQL
- Which SQL Formatter version are you using?
1.1.1

**Comment by nene** [comment]
I suspect you haven't set language option to `tsql`.

**Comment by inferrinizzard** [comment]
if vscode is unable to detect your file as tsql, you should use the SQLFlavourOverride option

**Comment by EvenC-tw** [comment]
It works after I set SQLFlavourOverride from `sql` to `tsql`, thanks.
