### ISSUE TITLE
TS1005: typescript parse error

### ISSUE THREAD

**Issue by jsx19950204** [sql-formatter-org/sql-formatter#419]
**Describe the bug**
![image](https://user-images.githubusercontent.com/22184137/187634747-8b44990a-f174-4868-b931-f674d83a692f.png)

**Expected behavior**
import type { ParamItems } from './formatter/Params';

**Actual behavior**
import { type ParamItems } from './formatter/Params';

**Usage**

- How are you calling / using the library? npm library
- What SQL language(s) does this apply to? sql
- Which SQL Formatter version are you using? 10.0.0

**Comment by nene** [comment]
Just released sql-formatter 10.1.0, which should eliminate this issue.

However, you should also consider upgrading TypeScript. TypeScript 4.5, which supports this syntax, was released about a year ago.
