### ISSUE TITLE
Unexpected ASTERISK token

### ISSUE THREAD

**Issue by jcgoette** [sql-formatter-org/sql-formatter#430]
**Describe the bug**
`SELECT dual.* FROM dual` causes web formatter to raise error.

**Expected behavior**

Format per usual:
```
SELECT
  dual.*
FROM
  dual
```

**Actual behavior**
An Unexpected Error Occurred

Parse error at token: * Unexpected ASTERISK token: {"type":"ASTERISK","raw":"*","text":"*","start":12,"end":13}. Instead, I was expecting to see one of the following: A ARRAY_IDENTIFIER token based on: array_subscript → ● %ARRAY_IDENTIFIER square_brackets property_access$subexpression$1 → ● array_subscript property_access → simple_expression %DOT ● property_access$subexpression$1 simple_expression$subexpression$1 → ● property_access simple_expression → ● simple_expression$subexpression$1 asteriskless_expression$subexpression$1 → ● simple_expression asteriskless_expression → ● asteriskless_expression$subexpression$1 select_clause$subexpression$1 → ● asteriskless_expression select_clause$subexpression$1$ebnf$2 select_clause → %RESERVED_SELECT ● select_clause$subexpression$1 clause$subexpression$1 → ● select_clause clause → ● clause$subexpression$1 expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2 statement → ● expressions_or_clauses statement$subexpression$1 main$ebnf$1 → main$ebnf$1 ● statement main → ● main$ebnf$1 A ARRAY_KEYWORD token based on: array_subscript → ● %ARRAY_KEYWORD square_brackets property_access$subexpression$1 → ● array_subscript property_access → simple_expression %DOT ● property_access$subexpression$1 simple_expression$subexpression$1 → ● property_access simple_expression → ● simple_expression$subexpression$1 asteriskless_expression$subexpression$1 → ● simple_expression asteriskless_expression → ● asteriskless_expression$subexpression$1 select_clause$subexpression$1 → ● asteriskless_expression select_clause$subexpression$1$ebnf$2 select_clause → %RESERVED_SELECT ● select_clause$subexpression$1 clause$subexpression$1 → ● select_clause clause → ● clause$subexpression$1 expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2 statement → ● expressions_or_clauses statement$subexpression$1 main$ebnf$1 → main$ebnf$1 ● statement main → ● main$ebnf$1 A IDENTIFIER token based on: identifier$subexpression$1 → ● %IDENTIFIER identifier → ● identifier$subexpression$1 property_access$subexpression$1 → ● identifier property_access → simple_expression %DOT ● property_access$subexpression$1 simple_expression$subexpression$1 → ● property_access simple_expression → ● simple_expression$subexpression$1 asteriskless_expression$subexpression$1 → ● simple_expression asteriskless_expression → ● asteriskless_expression$subexpression$1 select_clause$subexpression$1 → ● asteriskless_expression select_clause$subexpression$1$ebnf$2 select_clause → %RESERVED_SELECT ● select_clause$subexpression$1 clause$subexpression$1 → ● select_clause clause → ● clause$subexpression$1 expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2 statement → ● expressions_or_clauses statement$subexpression$1 main$ebnf$1 → main$ebnf$1 ● statement main → ● main$ebnf$1 A QUOTED_IDENTIFIER token based on: identifier$subexpression$1 → ● %QUOTED_IDENTIFIER identifier → ● identifier$subexpression$1 property_access$subexpression$1 → ● identifier property_access → simple_expression %DOT ● property_access$subexpression$1 simple_expression$subexpression$1 → ● property_access simple_expression → ● simple_expression$subexpression$1 asteriskless_expression$subexpression$1 → ● simple_expression asteriskless_expression → ● asteriskless_expression$subexpression$1 select_clause$subexpression$1 → ● asteriskless_expression select_clause$subexpression$1$ebnf$2 select_clause → %RESERVED_SELECT ● select_clause$subexpression$1 clause$subexpression$1 → ● select_clause clause → ● clause$subexpression$1 expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2 statement → ● expressions_or_clauses statement$subexpression$1 main$ebnf$1 → main$ebnf$1 ● statement main → ● main$ebnf$1 A VARIABLE token based on: identifier$subexpression$1 → ● %VARIABLE identifier → ● identifier$subexpression$1 property_access$subexpression$1 → ● identifier property_access → simple_expression %DOT ● property_access$subexpression$1 simple_expression$subexpression$1 → ● property_access simple_expression → ● simple_expression$subexpression$1 asteriskless_expression$subexpression$1 → ● simple_expression asteriskless_expression → ● asteriskless_expression$subexpression$1 select_clause$subexpression$1 → ● asteriskless_expression select_clause$subexpression$1$ebnf$2 select_clause → %RESERVED_SELECT ● select_clause$subexpression$1 clause$subexpression$1 → ● select_clause clause → ● clause$subexpression$1 expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2 statement → ● expressions_or_clauses statement$subexpression$1 main$ebnf$1 → main$ebnf$1 ● statement main → ● main$ebnf$1

**Usage**

- How are you calling / using the library?
  - Web
- What SQL language(s) does this apply to?
  - All as far as I can tell
- Which SQL Formatter version are you using?
  - Web

**Comment by nene** [comment]
Thanks for reporting. Turns out it's a regression caused by #424 which fixed #423.

Wrote the fix. Hopefully it'll be released soonish.

**Comment by nene** [comment]
Fixed in 10.5.1
