### ISSUE TITLE
[FORMATTING] Doesn't format code with postgres placeholders

### ISSUE THREAD

**Issue by cs-clarence** [sql-formatter-org/sql-formatter#435]
**Input data**
```sql
SELECT username, password FROM users WHERE username = $1;
```

**Expected Output**

```sql
SELECT 
    username, password 
FROM 
    users 
WHERE 
    username = $1;
```

**Actual Output**

```sql
SELECT username, password FROM users WHERE username = $1;
```

If I replace the placeholders with something else like `'some string'` then formatting works.

**Usage**

- How are you calling / using the library?
Using neovim with built-in lsp

- What SQL language(s) does this apply to?
Postgres

- Which SQL Formatter version are you using?
10.5.1

**Comment by nene** [comment]
I suspect the problem is that you haven't selected PostgreSQL as the SQL dialect to be formatted.

However, I'm not familiar with neovim etc to guide you in that.

You can test that it works in sql-formatter library by going to https://sql-formatter-org.github.io/sql-formatter/ and choosing Language: PostgreSQL from the dropdown on the left.

**Comment by cs-clarence** [comment]
> I suspect the problem is that you haven't selected PostgreSQL as the SQL dialect to be formatted.
> 
> However, I'm not familiar with neovim etc to guide you in that.
> 
> You can test that it works in sql-formatter library by going to https://sql-formatter-org.github.io/sql-formatter/ and choosing Language: PostgreSQL from the dropdown on the left.

Can confirm it works, same with vs code plugin too. I'll just find a way to change the dialect on my setup.

**Comment by cs-clarence** [comment]
For those who are using `neovim` and `null-ls` for formatting, you should provide whichever dialect your using as an argument to the formatter in your config.

```lua
null_ls.setup({
  debug = false,
  sources = {
    -- your other configurations
    formatting.sql_formatter.with({ extra_args = { "-l", "postgresql" } }),
  },
})
```
