### ISSUE TITLE
[FORMATTING] Parse error

### ISSUE THREAD

**Issue by veetallic** [sql-formatter-org/sql-formatter#441]
**Input data**
SELECT ('1' || '2') from dual;

**Expected Output**

```sql
SELECT 
  ('1' || '2') 
from 
  dual;
```

**Actual Output**

```sql
-- no sql
```

Error messages:
Unable to format SQL: Error: Parse error: Unexpected ""
Unable to format SQL: Error: Parse error: Unexpected "|| '2') from dual;"

**Usage**

- How are you calling / using the library? - Alt+Shift+F
- What SQL language(s) does this apply to? - Oracle SQL
- Which SQL Formatter version are you using? - v1.3.0 Windows

**Comment by nene** [comment]
This happens because the default SQL dialect doesn't support `||` operator. This bug has been fixed since in sql-formatter, but the fix hasn't yet made it into VSCode extension.

Anyway, as you're using Oracle SQL, you should select in the extension settings `SQLFlavour Override: plsql`
