### ISSUE TITLE
[FORMATTING] Redshift dialect fails when using :: to cast after v10.2.0

### ISSUE THREAD

**Issue by AlexAVL** [sql-formatter-org/sql-formatter#450]
**Input data**

Casting to any type using the `::` format. The simplest example is:

```sql
SELECT 1::float;
```

**Expected Output**

```sql
SELECT 1:: float; -- or similar
```

**Actual Output**

On every version of the parser over 10.2.0 the the parser throws a JS error.

```
Parse error: Unexpected "::float"
```

**Usage**

- How are you calling / using the library? Node 16
- What SQL language(s) does this apply to? Redshift (others untested)
- Which SQL Formatter version are you using? 10.3.0+

**Comment by nene** [comment]
Thanks for reporting.

Wasn't aware that Redshift also supports the type cast operator. Will fix.

**Comment by nene** [comment]
Should be fixed now in 10.7.1

**Comment by AlexAVL** [comment]
Thanks for fixing that. I can confirm it's working in 10.7.1.

**Comment by aleclarson** [comment]
I'm seeing this with Postgres too

**Comment by nene** [comment]
> I'm seeing this with Postgres too

Please be more specific than that. I fixed this for Redshift based on how it was already implemented for Postgres.
