### ISSUE TITLE
Wrong Documentation for CROSS JOIN

### ISSUE THREAD

**Issue by primeapple** [sql-formatter-org/sql-formatter#468]
**Describe the bug**
While adding the Snowflake JOIN specificatin to the [Join Wikipage](https://github.com/sql-formatter-org/sql-formatter/wiki/FROM-clause) I came across a wrong definition of `CROSS JOIN`.

According to the Wiki, this is the specification for a `CROSS JOIN`:
```
table_reference CROSS JOIN table_reference [join_specification]
```
However I think the `[join_specification]` is wrong here. According to the [linked SQL Standard](https://jakewheat.github.io/sql-overview/sql-2008-foundation-grammar.html#_7_7_joined_table) the `CROSS JOIN` does NOT have a `[join_specification]`

This is also true for at least Snowflake.
Please have a look at these pages.

**Comment by nene** [comment]
Yep, you're right. Fixed the syntax docs in wiki.

For the purposes of the formatter, this difference doesn't really matter a lot. That's why the I probably made the mistake when documenting this syntax originally.
