### ISSUE TITLE
Feature Request: Inappropriate placement of comments

### ISSUE THREAD

**Issue by Chasen-Zhang** [sql-formatter-org/sql-formatter#476]
**Describe the Feature**
Can this type of comment be moved later, as illustrated in following figure:
![image](https://user-images.githubusercontent.com/15354455/192934583-cbdf98a7-8906-4406-a861-ad2e7673d215.png)

**Why do you want this feature?**
I think it's more reasonable

pref: https://www.dpriver.com/pp/sqlformat.htm

eg sql:

INSERT INTO t666x
select Rand()::string, -- c1
            Rand()::string, -- c2
            Rand()::string, -- c3
            Rand()::string, -- c4
            Rand()::string, -- c5
            Rand()::string, -- c6
            Rand()::string, -- c7
            Rand()*10000000, -- c8
            Rand()*10000000, -- c9
            Rand()::string, -- c10
            Rand()::string, -- c11
            Rand()::string, -- c12
            Rand()::string, -- c13
            Rand()::string, -- c14
            Rand()::string, -- c15
            Rand()::string, -- c16
            Rand()::string, -- c17
            Rand()::string, -- c18
            Rand()::string, -- c19
            Rand()::string, -- c20
            Rand()::string, -- c21
            Parse_json('{"a":1,"b":{"c":2}}'), -- c22
            Parse_json('{"a":1,"b":{"c":2}}'), -- c23
            Rand()::string, -- c24
            Rand()::string, -- c25
            Rand()::string  -- c26
           from numbers(10)
           ;
![image](https://user-images.githubusercontent.com/15354455/192934859-fba18f85-6090-4eed-b4bc-26ed81923612.png)

translate into
![image](https://user-images.githubusercontent.com/15354455/192934737-9bcfeef0-dcb7-4730-8653-332923c6389f.png)

**Comment by nene** [comment]
I don't understand what exactly you're asking for. Please try to write your request in the form:

- what's your input SQL?
- how does SQL Formatter format it currently?
- how would you like it to be formatted instead?

**Comment by nene** [comment]
Closing this as can't repro / not enough info.
