### ISSUE TITLE
First comment in file gets indented by single space

### ISSUE THREAD

**Issue by codazzo** [sql-formatter-org/sql-formatter#481]
**Describe the Feature**
It would be  nice to have an option which configures the amount of whitespace inserted before comments.

**Why do you want this feature?**
Certain tools rely on comments for metadata. I'm using `dbmate`, which uses [comments](https://github.com/amacneil/dbmate#creating-migrations) to annotate where `up` and `down` migrations start and end. It currently breaks while parsing SQL formatted by this tool.

**Comment by codazzo** [comment]
On closer inspection, it appears a whitespace is only inserted if a comment is the first line in the file. Is there a way to disable _that_ ?

**Comment by nene** [comment]
I suppose that by whitespace you mean empty lines. By default the formatter adds one empty line between statements, though the end of statement is determined by a semicolon. Other than that, there shouldn't be any extra empty lines inserted. You can configure the amount of empty lines between statements through [linesBetweenQueries](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/linesBetweenQueries.md) option.

Related to this there's another feature request for a possible improvement: #329

**Comment by codazzo** [comment]
Apologies for the late reply! I created a sandbox to make the problem clearer: https://codesandbox.io/s/blissful-aryabhata-mfnwsb?file=/src/App.js

The first line has an extra whitespace (not newline) in front.

**Comment by nene** [comment]
OK. I see now. The problem is that given this input SQL:

```sql
-- comment1
-- comment2
```

the formatter outputs the following:

```sql
 -- comment1
-- comment2
```

That's a bug. Should not happen. A problem caused by logic that decides whether to place the comment on a separate line or at the end of the preceding line. It mistakenly thinks it should go at the end of a preceding line because there's no newline before the comment, but that's not a correct assumption for the very first line of code.

**Comment by nene** [comment]
Fixed now in 11.0.2 release

**Comment by codazzo** [comment]
Excellent, thank you very much!
