### ISSUE TITLE
I have a query with [Big Query's REGEXP_CONTAINS](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#regexp_contains)

### ISSUE THREAD

**Issue by zendesk-johnhenry** [sql-formatter-org/sql-formatter#492]
the behavior below is still happening.        

I have a query with [Big Query's REGEXP_CONTAINS](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#regexp_contains) 
like this
```sql
SELECT field1 FROM table1 WHERE REGEXP_CONTAINS(field1, r"value")
```
then after format it turns to
```sql
SELECT
  field1
FROM
  table1
WHERE
  REGEXP_CONTAINS(field1, r "value")
```
there is a space between `r` and `"value"` which break the query.

_Originally posted by @tuanngominh in https://github.com/sql-formatter-org/sql-formatter/issues/33#issuecomment-363677401_

**Comment by nene** [comment]
Just select "bigquery" as the language you're formatting:

```js
format('SELECT r"value"', { language: 'bigquery' });
```
