### ISSUE TITLE
[FORMATTING] Unexpected "[abc].[xyz]"

### ISSUE THREAD

**Issue by hungton24hdev** [sql-formatter-org/sql-formatter#504]
**Input data**

Which SQL and options did you provide as input?

```sql
-- TRUNCATE TABLE [abc].[xyz];
```

**Expected Output**

```sql
-- TRUNCATE TABLE [abc].[xyz];
```

**Actual Output**
Throw error
![image](https://user-images.githubusercontent.com/81126276/197092292-e3297a3d-58e6-4f73-b3d1-a6820a3c99be.png)

How can I fix this issue?

**Comment by nene** [comment]
Just select an appropriate SQL dialect:

![Screenshot 2022-10-21 at 11 24 25](https://user-images.githubusercontent.com/118201/197149622-51305330-2beb-468f-be96-5bcd4dec9c28.png)

You're probably using Transact-SQL.
