### ISSUE TITLE
[FORMATTING] sql parse error

### ISSUE THREAD

**Issue by Kurt-Shiwz** [sql-formatter-org/sql-formatter#506]
**Input data**

Which SQL and options did you provide as input?

```sql
118    ,exp_interact_rate    DOUBLE COMMENT 'x1'
119    ,7d_exp_interact_rate DOUBLE COMMENT 'x2'
120    ,avg_exp              DOUBLE COMMENT 'x3'
```

**Expected Output**

```sql

```

**Actual Output**

```sql
Unable to format SQL: Error: Parse error: Unexpected "7d_exp_int" at line 119 column 6
```

**Usage**

- How are you calling / using the library?
```
F1 -> Format Document
```

- What SQL language(s) does this apply to?
```
sql
```

- Which SQL Formatter version are you using?
```
v1.4.0
```

**Comment by nene** [comment]
Sorry, but this doesn't look like valid SQL to me.

Perhaps you're trying to format only a part of a larger SQL statement, this is not supported.

**Comment by nene** [comment]
Also, you're likely using some dialect of SQL, like PostgreSQL / MySQL / SQLite, not just a generic SQL.

And finally, you seem to be using the library through VSCode plugin, which is currently at 1.4.0 version. SQL Formatter itself is already at 11.0.2 :)

**Comment by Kurt-Shiwz** [comment]
> Sorry, but this doesn't look like valid SQL to me.
> 
> Perhaps you're trying to format only a part of a larger SQL statement, this is not supported.

i delete some code and leave that
```
CREATE TABLE IF NOT EXISTS abc.table1
(
    7d_exp_interact_rate DOUBLE COMMENT 'x2'
)
;
```

output
```
Unable to format SQL: Error: Parse error: Unexpected "7d_exp_int" at line 3 column 5
```

**Comment by Kurt-Shiwz** [comment]
> Also, you're likely using some dialect of SQL, like PostgreSQL / MySQL / SQLite, not just a generic SQL.
> 
> And finally, you seem to be using the library through VSCode plugin, which is currently at 1.4.0 version. SQL Formatter itself is already at 11.0.2 :)

yes,not standard sql. Format use `prettier sql vscode v1.4.0`

**Comment by Kurt-Shiwz** [comment]
> Sorry, but this doesn't look like valid SQL to me.
> 
> Perhaps you're trying to format only a part of a larger SQL statement, this is not supported.

must write like that \`7d_exp_interact_rate\`

```
CREATE TABLE IF NOT EXISTS abc.table1
(
    `7d_exp_interact_rate` DOUBLE COMMENT 'x2'
)
PARTITIONED BY 
(
    p                    STRING COMMENT 'x4'
)
;
```

**Comment by nene** [comment]
You need to select the specific SQL dialect you want to format.

With the VSCode plugin. Go to settings -> Prettier-SQL: SQLFlavourOverride -> select your SQL dialect e.g. MySQL.
