### ISSUE TITLE
Feature Request: Add a custom dictionary for auto-complete

### ISSUE THREAD

**Issue by Yangph** [sql-formatter-org/sql-formatter#508]
**Describe the Feature**
At present, there is an auto-complete function. Can you add a custom dictionary to realize automatic filling of tables and columns?

**Why do you want this feature?**
Enrich autocomplete to make it smarter

**Comment by nene** [comment]
Sorry, but this is really out of the scope for a code formatter. Plus we don't really have the information about tables and columns.
