### ISSUE TITLE
[FORMATTING] Parse error at token: FROM at line 1 column 20 Unexpected RESERVED_CLAUSE token: limit

### ISSUE THREAD

**Issue by xuoutput** [sql-formatter-org/sql-formatter#512]
**Input data**

Which SQL and options did you provide as input?

```sql
select uuid, limit from snap_server where ("uuid" = "9655a4")
```

**Expected Output**

```sql
select
  uuid,
  limit
from
  snap_server
where
  ("uuid" = "9655a4")
```

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/16385443/199527620-330a9dff-ee36-4307-b420-74e99e5f63a3.png">

**Actual Output**

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/16385443/199527419-b346015b-cb48-4491-b9ff-4f4512641b92.png">

**Usage**

- How are you calling / using the library?
- What SQL language(s) does this apply to?
- Which SQL Formatter version are you using?

11.0.2

**Comment by xuoutput** [comment]
https://github.com/sql-formatter-org/sql-formatter/issues/302

**Comment by nene** [comment]
I wonder which SQL dialect are you using that allows this syntax? Even PostgreSQL doesn't seem to doesn't allow this syntax, and Postgres is super-forgiving in regards to using reserved keywords as column names.

**Comment by xuoutput** [comment]
> I wonder which SQL dialect are you using that allows this syntax? Even PostgreSQL doesn't seem to allow this, and Postgres is super-forgiving in regards to using reserved keywords as column names.

thanks
