### ISSUE TITLE
[FORMATTING] Postgresql dialect cannot parse query containing input parameters

### ISSUE THREAD

**Issue by petrahume** [sql-formatter-org/sql-formatter#528]
**Input data**

Which SQL and options did you provide as input?

```sql
insert into invitation (organization_id, email, role, accepted)
values
  :invitations on conflict on constraint invitation_email_key do nothing returning id,
  organization_id as "organizationId", email, role, accepted;
```

**Expected Output**

```sql
insert into
  invitation (organization_id, email, role, accepted)
values
  :invitations on conflict on constraint invitation_email_key do nothing returning id,
  organization_id as "organizationId",
  email,
  role,
  accepted;
```

**Actual Output**

 ```Error: Parse error: Unexpected ":invitatio" at line 8 column 3```

**Usage**

- How are you calling / using the library?
```javascript
     const formattedContent = formatDialect(migrationFileContent, {
        dialect: postgresql,
        linesBetweenQueries: 1,
        keywordCase: 'lower',
      })
```
- What SQL language(s) does this apply to?

`postgresql` (I am using https://github.com/adelsz/pgtyped)

- Which SQL Formatter version are you using? `v12.0.1`

**Additional Remarks:** 
Formatting works on the given example when `sqlite` dialect is used.
This example worked when using `postgres` dialect in older versions  (`9.2.0` downwards)

**Comment by nene** [comment]
Use the [paramTypes](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/paramTypes.md) config option to configure what sort of parameter syntax you need. For example:

```js
formatDialect(sql, {
  paramTypes: { named: [':'] }
});
```
