### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by adelriosantiago** [sql-formatter-org/sql-formatter#536]
When importing sql-formatter I get the error "You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders". Is there any specific loader we should use for sql-format to run?

The full error message is:

> ./node_modules/sql-formatter/lib/formatter/ExpressionFormatter.js 11:9
> Module parse failed: Unexpected token (11:9)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | /** Formats a generic SQL expression */
> | export default class ExpressionFormatter {
> >   inline = false;
> |   nodes = [];
> |   index = -1;

Related: https://github.com/sql-formatter-org/sql-formatter/issues/502

**Comment by nene** [comment]
As I pointed out in the linked issue, you might be better off looking for a generic advice about configuring Webpack from elsewhere.

You probably want to use the [babel loader](https://github.com/babel/babel-loader), though I would assume you are already using that. And with babel, you should get the class-properties syntax support by just using `@babel/preset-env`.
