### ISSUE TITLE
Parse error: Unexpected '@...'

### ISSUE THREAD

**Issue by muuvmuuv** [sql-formatter-org/sql-formatter#537]
**Describe the bug**

Using `set @var = ();` results in a parsing error.

**Expected behavior**

Treat as custom var.

**Actual behavior**

Parsing error.

**Usage**

- VS Code
- What SQL language(s) does this apply to?
- Which SQL Formatter version are you using?

**Comment by nene** [comment]
Please see: https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-

**Comment by muuvmuuv** [comment]
Oh I overread this part "Or when using the VSCode extension: Settings -> Prettier-SQL: SQLFlavourOverride." sorry!
