### ISSUE TITLE
[VSCODE] Extension is not available on the VSCode Marketplace

### ISSUE THREAD

**Issue by rainecheck** [sql-formatter-org/sql-formatter#541]
**Describe the bug**
Extension is not available on the VSCode Marketplace.
- ID is listed in README.md of this repo, and of sql-formatter-vscode, as "Prettier-SQL" but no such extension appears in their search.
- No link to the marketplace is provided.
- Nothing explicit saying "This extension is not available on the Marketplace and must be compiled manually".

**Expected behavior**
Clarification on if the extension not being in the Marketplace is intentional or a link to the current version of the extension in the marketplace.

**Comment by inferrinizzard** [comment]
Hi, the extension is available here: https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode
