### ISSUE TITLE
Feature Request: Format multiple files in-place

### ISSUE THREAD

**Issue by fenuks** [sql-formatter-org/sql-formatter#552]
**Describe the Feature**
`sql-formatter` accepts only one file as an argument. It would be very convenient to be able to invoke it like so:
```
sql-formatter --inplace **/*.sql
```

**Why do you want this feature?**
I would like to run sql-formatter in a githook. It would be also useful if one wishes to reformat all files in a directory. Name of new flag might be different, there is no standard way. prettier for instancje uses `-w --write`

**Comment by nene** [comment]
Thanks fenuks. This is a sensible feature request.

However, the functionality can easily be achieved with a simple shell script. That's likely the reason why no such functionality has been implemented so far. Though achieving it in cross-platform way is probably somewhat trickier.

I am willing to accept a pull request for adding such a feature, however, I'm currently concentrating my efforts on writing a [new and better SQL formatting tool.](https://github.com/nene/prettier-plugin-sql-cst) So I'd rather not add new features to this library if I can avoid it.

**Comment by fenuks** [comment]
I agree that workarounds are possible, nonetheless it would be best to have it built-in for ergonomics. Unfortunately I'm not familiar with JS ecosystem, but I will try to add this feature. If not, I will simply write a loop in bash.

Very interested about new tool, there is shortage of good SQL formatters.

**Comment by nene** [comment]
I'm closing this. There's now a new flag `--fix` which will be useful for formatting a file in-place.

Support for multiple files is currently not planned.
