### ISSUE TITLE
THEN on newline

### ISSUE THREAD

**Issue by lorrie27** [sql-formatter-org/sql-formatter#553]
Request to add an option to put THEN on a newline under WHERE. This is a standard where I work and may be a standard at other companies.

**Comment by nene** [comment]
You should be more specific than that. Would you expect:

```sql
SELECT
  CASE foo
    WHEN 1
    THEN 'yes'
    WHEN 2
    THEN 'no'
  END
```

or would you expect:

```sql
SELECT
  CASE foo
    WHEN 1
      THEN 'yes'
    WHEN 2
      THEN 'no'
  END
```
