### ISSUE TITLE
[VSCODE] Allow specifying config file in extension settings

### ISSUE THREAD

**Issue by ahobsonsayers** [sql-formatter-org/sql-formatter#562]
**Describe the Issue**
The VSCode extension does not allow us to specify a config file to be used for formatter settings, instead requiring us to use the extension settings in the VSCode `settings.json` to configure behaviour.

I would be great if we could specify our settings externally to `settings.json` in their own dedicated config file, then setup the extension to use that file.

**Comment by nene** [comment]
Thanks. I think it's a nice feature request.

However, it's a fair bit of work to implement, and I'm currently concentrating on doing [a complete rewrite of this whole formatter.](https://github.com/nene/prettier-plugin-sql-cst) If you were to implement such a feature, I would be happy to accept a pull request to https://github.com/sql-formatter-org/sql-formatter-vscode

You probably would also want @inferrinizzard (who's really the main maintainer of the extension) to be on board with that, and he's been kind of away lately. If you manage to get his attention, he might get it into a released version of the extension.
