### ISSUE TITLE
[FORMATTING] newline after FROM and NULL in IS DISTINCT FROM NULL

### ISSUE THREAD

**Issue by benasher44** [sql-formatter-org/sql-formatter#564]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT table1.id FROM table1
LEFT OUTER JOIN table2 ON table2.table1_id = table1.id
WHERE NOT (COALESCE(interview_stage.* IS DISTINCT FROM NULL, FALSE))
```

**Expected Output**

// something like this that shows the `IS DISTINCT FROM NULL` part on a single line
```sql
SELECT
      table1.id
    FROM
      table1
      LEFT OUTER JOIN table2 ON table2.table1_id = table1.id
    WHERE
      NOT (
        COALESCE(
            table2.* IS DISTINCT FROM NULL,
            FALSE
        )
      )
```

**Actual Output**

```sql
SELECT
      table1.id
    FROM
      table1
      LEFT OUTER JOIN table2 ON table2.table1_id = table1.id
    WHERE
      NOT (
        COALESCE(
          table2.* IS DISTINCT
          FROM
            NULL,
            FALSE
        )
      )
```

**Usage**

- How are you calling / using the library? Using it in a test to show a nicely formatted expected output
- What SQL language(s) does this apply to? Postgresql
- Which SQL Formatter version are you using? 12.1.0

**Comment by nene** [comment]
Thanks for reporting.

While this is a problem that demonstrates some of the fundamental issues that this formatter library has, I think this particular case should be relatively easy to patch up.

**Comment by benasher44** [comment]
Amazing thank you!

**Comment by nene** [comment]
Released the fix in 12.1.1.

**Comment by benasher44** [comment]
@nene thanks again for fixing! I pulled the latest sql-formatter, and I'm still seeing this issue. I even tried the sample you used in the test, and it's putting newlines before `FROM`. Check out the codesandbox (console output) here: https://codesandbox.io/s/bold-hofstadter-6099hg?file=/src/index.ts

**Comment by nene** [comment]
This syntax is specific to Postgres and a few other dialects. Just specify the correct SQL language:

```js
format("SELECT x IS DISTINCT FROM y, x IS NOT DISTINCT FROM y", {language: "postgresql"})
```

**Comment by benasher44** [comment]
Ah that did it. Thanks!!
