### ISSUE TITLE
Feature Request: allow `@param_name` formatting

### ISSUE THREAD

**Issue by Davincible** [sql-formatter-org/sql-formatter#569]
**Describe the Feature**
For PostgreSQL

With [sqlc](https://github.com/kyleconroy/sqlc), you can set a name parameter with `@my_named_param`, much like `$1`. Currently whenever the formatter encounters this it adds a space in between the `@` sign and the text, which is invalid syntax and thus rendering it unusable for sqlc compiled SQL files using this special syntax. I would like the formatter to not add that extra space there.

**Why do you want this feature?**
Either change the default behavior not to add a space after a `@` sign or add an optional option to change this behavior.

**Comment by nene** [comment]
Use the [paramTypes][] option. For example:

```js
paramTypes: [{named: ['@']}],
```

[paramTypes]: https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/paramTypes.md
