### ISSUE TITLE
[FORMATTING] New line created after "create table"

### ISSUE THREAD

**Issue by kiwicopple** [sql-formatter-org/sql-formatter#570]
I am finding it hard to place this one as a bug, because I'm 90% certain the behavior has changed (because our GitHub actions started failing), but it looks like it's intentional from the tests, and has been this way for a while.

**Input data**

Which SQL and options did you provide as input?

```sql
create table profiles (
    id bigint primary key,
    name text not null,
    dob date
);
```

**Expected Output**

```sql
create table profiles (
    id bigint primary key,
    name text not null,
    dob date
);
```

**Actual Output**

```sql
create table
  profiles (
    id bigint primary key,
    name text not null,
    dob date
  );
```

As I mention above, perhaps this is intentional. If so, is there a way configure the formatting so that there is not a line-drop between the `create table` and the name of the table?

**Usage**

- How are you calling / using the library? Using npm + Prettier - runs prettier on save
- What SQL language(s) does this apply to? `postgresql`
- Which SQL Formatter version are you using? The latest ( but I also tried several earlier versions)

**Thank you**

Also, thank you for maintaining this library 🙏

**Comment by nene** [comment]
This is duplicate of #495.

I don't really like this behavior either, but it's unlikely to change in this formatter.

I have started work on a [new SQL formatting tool](https://github.com/nene/prettier-plugin-sql-cst) which already formats `create table` in the way you're proposing here. It doesn't directly support Postgres, but most of the usual SQL syntax should probably work. Perhaps you wanna give it a try.

**Comment by kiwicopple** [comment]
thanks @nene - I'll close this one. Sorry for the dupe

**Comment by kiwicopple** [comment]
prettier-plugin-sql-cst looks great - we'll try it out 👍
