### ISSUE TITLE
[VSCODE] Compatibility with VSCode Snowflake extension 

### ISSUE THREAD

**Issue by athal7** [sql-formatter-org/sql-formatter#571]
**Describe the bug**
The [Snowflake extension ](https://marketplace.visualstudio.com/items?itemName=snowflake.snowflake-vsc) classifies files ending in .sql as a Language Mode of “Snowflake SQL” in order to support in-editor query execution. When trying to format those files using the Prettier SQL VSCode extension, an error shows up: “There is no formatter for ‘snowflake-sql’ files installed.”

**To Reproduce**
Attempt to format a .sql file classified as Snowflake SQL language mode using the Prettier SQL VSCode extension.

**Expected behavior**
Format the file

**Screenshots**
N/A

**Usage**

- What SQL language(s) does this apply to?  

Snowflake SQL

- What VSCode version are you using?

1.75.1

- What are your currently configured VSCode settings for the `prettier-sql` extension, if relevant to the issue?

n/a

**Additional context**

None

**Comment by suzu-prog** [comment]
+1
I’m in the same state.

**Comment by nene** [comment]
This is now finally fixed in 2.1.0 version of [the new vscode extension](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc).
