### ISSUE TITLE
Feature Request: Software packages for each OS

### ISSUE THREAD

**Issue by kishaningithub** [sql-formatter-org/sql-formatter#572]
**Describe the Feature**
It would be great if this tool can be published into the package managers to simplify installation and upgrade process. I am personally interested to have this as a [homebrew](https://brew.sh/) first as it supports both mac and linux.

**Why do you want this feature?**
I use [homebrew](https://brew.sh/) as my package manager in my laptop which enables be to install and update all installed packages with a single command. It would be great if this tool can be made available as a homebrew package

**Comment by nene** [comment]
Hi Kishan,

I would not mind making this available as a homebrew package. I'm willing to accept a pull request to add such a capability. Though frankly I have no idea what it takes to create a homebrew package. I would guess packaging for homebrew (or any other package manager) shouldn't necessarily be part of this repository.

But I'm personally not keen on investigating and implementing this. FWIW, this tool is already available on all platforms through npm.
