### ISSUE TITLE
Postgres Dollar-Quoted String Constants

### ISSUE THREAD

**Issue by magick93** [sql-formatter-org/sql-formatter#576]
The use of  Dollar-Quoted String Constants causes crash

For example:

```
COMMENT ON TABLE comment_type IS $$This is a comment for a table.$$;
```

**Expected behavior**
What did you expect to happen?

**Actual behavior**
The command ` sql-formatter CommentType.json.sql --fix` crashed due to Dollar quotes.

See https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS

**Usage**

- How are you calling / using the library? ` sql-formatter CommentType.json.sql --fix`
- What SQL language(s) does this apply to? Postgres 
- Which SQL Formatter version are you using? `12.1.3`

**Comment by nene** [comment]
Just specify the correct dialect with `--language postgresql` option.

**Comment by magick93** [comment]
Thanks, yes, `--language postgresql` made it work.
