### ISSUE TITLE
[FORMATTING] Modulo Operator Formatting issue

### ISSUE THREAD

**Issue by Syntax-Read3r** [sql-formatter-org/sql-formatter#578]
**Input data**

Which SQL and options did you provide as input?

SELECT title, released_year
FROM books
where
    released_year >= 2000
    AND (released_year % 2) != 0;

Returned Error
Unable to format SQL: Error: Parse error: Unexpected "% 2) != 0;" at line 87 column 24

- How are you calling / using the library?
- What SQL language(s) does this apply to? MySQL
- Which SQL Formatter version are you using? MySQL v8

**Comment by nene** [comment]
See: https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-

**Comment by Syntax-Read3r** [comment]
First and foremost thanks for creating this extension. 
Prior to raising the bug issue, I had attempted multiple things to resolve it
such as the code below. The issue I ran into was, the problem was fixed BUT
your extension was no longer be called upon by the IDE.

`	
"[sql]": {
		"editor.defaultFormatter": "mtxr.sqltools"
		//	"editor.defaultFormatter": "inferrinizzard.prettier-sql-vscode"
	},
	"Prettier-SQL.SQLFlavourOverride": "sql",

`

I don't know what the issue, is. If you can spot it, That would be great.

**Comment by nene** [comment]
Sorry, I don't quite understand your description of the issue.

What I can spot is that you're using `"Prettier-SQL.SQLFlavourOverride": "sql"` but you really should set this to MySQL: `"Prettier-SQL.SQLFlavourOverride": "mysql"`, to be able to properly parse MySQL code.

**Comment by nene** [comment]
You can also try to format your code here: https://sql-formatter-org.github.io/sql-formatter/

If the problem is also present there, it's an issue in the core library (though, make sure to also choose the proper SQL dialect first). If not, then it's a problem in the VSCode extension or its configuration.

**Comment by Syntax-Read3r** [comment]
I will tell you something. I don't know how I fixed the bug. But it's now fixed. It process involved a lot of uninstalling extensions and reinstalling them. Thanks for the help.
