### ISSUE TITLE
Feature Request (vscode): Support SQL in files of other languages

### ISSUE THREAD

**Issue by mathe42** [sql-formatter-org/sql-formatter#581]
In many cases you have SQL inside of PHP or other languages. Here formating works by selecting the complete SQL string and format it.

But I would like to change the bahavior of this format:

If I have this code:

```php
<?php

if(true) {
  $sql1 = "SELECT * FROM user WHERE age >= 18 AND gender = 'm'";
}
```

I format it it looks like this:

```php
<?php

if(true) {
  $sql1 = "SELECT
  *
FROM
  USER
WHERE
  age >= 18
  AND gender = 'm'";
}
```

But I would like to have it like this:

```php
<?php

if(true) {
  $sql1 = "SELECT
    *
  FROM
    USER
  WHERE
    age >= 18
    AND gender = 'm'";
}
```

So as the line with the SELECT keyword is ONCE indented I want to have ONE additional indent for all other lines.

Same with more indents.

I propose to add a specific flag in the extension to change to this behaviour.

**Comment by nene** [comment]
Glad you found a solution.

> the string has to start with a keyword... (For example " SELECT..." doesn't work...)

This seems like a bug in the syntax highlighting to me. Whitespace really shouldn't me significant in this case. I'd say report this as an issue to to whoever maintains this PHP syntax highlighting.
