### ISSUE TITLE
Feature Request: Add a configuration option that allows to display muiltle filed in one line instead of displaying each field on a separate line

### ISSUE THREAD

**Issue by forrany** [sql-formatter-org/sql-formatter#585]
**Describe the Feature**

The current formatting separates each field in the SQL statement into an individual line. However, when there are many fields in the query, displaying each field on a separate line takes up a lot of space, making it difficult to view the complete SQL statement. Is it possible to add a configuration option that allows me to change the formatting so that, for example, each line displays n fields before wrapping to the next line, rather than displaying each field on a separate line?"

```sql
SELECT environment, coordinator, uptime,
    nodeVersion, starting, dataid,
    bizid, beat, ip,
    cloudid, datetime, gseindex,
    utctime, type, timezone,
    data, dtEventTime, dtEventTimeStamp,
    thedate, localTime
FROM xxx
WHERE thedate='20230328'
LIMIT 100
```

```sql
SELECT
  environment,
  coordinator,
  uptime,
  nodeVersion,
  starting,
  dataid,
  bizid,
  beat,
  ip,
  cloudid,
  datetime,
  gseindex,
  utctime,
  type,
  timezone,
  data,
  dtEventTime,
  dtEventTimeStamp,
  thedate,
  localTime
FROM
  xxx
WHERE
  thedate = '20230328'
LIMIT
  100
```

**Why do you want this feature?**
As shown above

**Comment by nene** [comment]
Thanks for the feature request, but unfortunately I have to say that such a feature is very unlikely to happen.

For the time being I'm not really doing any new feature developments for this formatter. Unless it's something simple that's highly requested, and this sort of formatting has never been requested before (as far as I remember).

I'm working on [a brand new SQL formatting tool](https://github.com/nene/prettier-plugin-sql-cst), but as that one is even more opinionated than this, I don't see place for such a feature in there either.
