### ISSUE TITLE
Unable to format a PostgreSQL function

### ISSUE THREAD

**Issue by nbouvrette** [sql-formatter-org/sql-formatter#589]
**Describe the bug**
While trying to format this PostgreSQL function:

```sql
CREATE FUNCTION test(character varying) RETURNS boolean
    LANGUAGE sql
    AS $_$
select exists (select 1 from "test2" where value = $1 and type = 'testType');
$_$;
```

**Expected behavior**
I would expect the formatter to not throw errors for valid SQL syntax.

**Actual behavior**
I am getting the following error: `Error: Parse error: Unexpected "$_$`

**Usage**
I am using it with the [prettier-plugin-sql](https://github.com/un-ts/prettier) which auto-formats my projects using Prettier.

See the original issue here: https://github.com/un-ts/prettier/issues/242

**Comment by nene** [comment]
Just specify PostgreSQL as the SQL dialect you're formatting. With prettier-plugin-sql this should be done though `language: 'postgresql'`.

**Comment by nbouvrette** [comment]
@nene Thanks that did the trick! sorry for missing this earlier.
