### ISSUE TITLE
Feature Request: lowercase types, uppercase keywords

### ISSUE THREAD

**Issue by Coachonko** [sql-formatter-org/sql-formatter#591]
**Describe the Feature**
Currently, keywords can be turned uppercase/lowercase. This setting also acts on types. 

mysql_pump outputs types in lowercase and keywords in uppercase, I would like to use the same style in my files. **Not by preserving what I type**, but allowing me to type all lowercase and get sql-formatter to turn **only** keywords to uppercase and leaving types in lowercase. If I paste some code in, and this code happens to have uppercase types, I would like sql-formatter to turn these types to lowercase, just the types.

**Why do you want this feature?**
mysql_pump and pg_dump use this formatting style, it's readable and I like it.

**Comment by nene** [comment]
Not really related to VSCode plugin.

Related to issue about the case for function names: https://github.com/sql-formatter-org/sql-formatter/issues/237

Technically possible, but will take quite a bit of work. As I'm currently not planning to implement any new features, it's unlikely to happen though.

**Comment by nene** [comment]
I'm closing this issue in favor of #237
