### ISSUE TITLE
[VSCODE] Respect .editorconfig insert_final_newline

### ISSUE THREAD

**Issue by shishkin** [sql-formatter-org/sql-formatter#592]
**Describe the bug**
I have `insert_final_newline = true` in `.editorconfig` and Prettier mostly respects it in other types of files, but `.sql` files terminate without a new line.

**To Reproduce**

1. Add `insert_final_newline = true` in `.editorconfig`
2. Format SQL file

**Expected behavior**
File to terminate with a system's new line character sequence.

**Usage**

- What SQL language(s) does this apply to? SQL
- What VSCode version are you using? 1.77.3
- What are your currently configured VSCode settings for the `prettier-sql` extension, if relevant to the issue? No relevant settings found.

**Comment by nene** [comment]
Yeah, unfortunately the name is misleading. This extension really has nothing to do with [Prettier](https://prettier.io/).

The sql-formatter command-line tool does insert a newline at the end of its output. The editor plugin probably just takes the output from the library and doesn't add a final newline. Should fix.

I'm also building a new SQL formatting tool that is [implemented as a Prettier plugin](https://github.com/nene/prettier-plugin-sql-cst). It does add a final newline. However the final newline behavior is actually not configurable in Prettier. At least [Prettier docs about .editorconfig](https://prettier.io/docs/en/configuration.html#editorconfig) state that these options can't be configured:

```
# Non-configurable Prettier behaviors
charset = utf-8
insert_final_newline = true
```

**Comment by shishkin** [comment]
I see. I will try the new extension. It looks promising, though I would need [Postgres syntax](https://github.com/nene/prettier-plugin-sql-cst/issues/4).

**Comment by nene** [comment]
I've now modified the [new vscode-extension](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc) to auto-detect whether a newline should be added to the end of the file or not.
