### ISSUE TITLE
[FORMATTING] Multi-column alter formatting issues

### ISSUE THREAD

**Issue by innermatrix** [sql-formatter-org/sql-formatter#598]
**Input data**

Which SQL and options did you provide as input?

```sql
alter table app_public.insurance_providers
alter column in_network set not null,
alter column created_dt set not null,
alter column updated_dt set not null;
```

**Expected Output**

```sql
alter table app_public.insurance_providers
alter column in_network set not null,
alter column created_dt set not null,
alter column updated_dt set not null;
```

**Actual Output**

```sql
alter table
	app_public.insurance_providers
alter column
	in_network
set not null
,
alter column
	created_dt
set not null
,
alter column
	updated_dt
set not null;
```

**Usage**

- How are you calling / using the library? `$ npx sql-formatter file.sql`
- What SQL language(s) does this apply to? `postgresql`
- Which SQL Formatter version are you using? 12.2.0

**Comment by nene** [comment]
Thanks for reporting, but I don't get the output you're getting.

Running `npx sql-formatter file.sql` gives me:

```
alter table app_public.insurance_providers
alter column in_network
set
  not null,
alter column created_dt
set
  not null,
alter column updated_dt
set
  not null;
```

And running `npx sql-formatter --language postgresql file.sql` gives me:

```
alter table app_public.insurance_providers
alter column in_network
set not null,
alter column created_dt
set not null,
alter column updated_dt
set not null;
```

Neither is ideal, but definitely better than what you're getting.
