### ISSUE TITLE
[FORMATTING] Named arguments in BigQuery

### ISSUE THREAD

**Issue by pokutuna** [sql-formatter-org/sql-formatter#602]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT MAKE_INTERVAL(1, day=>2, minute => 3)
```

**Expected Output**

```sql
SELECT
  MAKE_INTERVAL(1, day => 2, minute => 3)
```

**Actual Output**

```sql
SELECT
  MAKE_INTERVAL(1, day = > 2, minute = > 3)
```

**Usage**

- How are you calling / using the library?
  - `$ npx -p sql-formatter@12.2.0 sql-formatter -l bigquery file.sql`
- What SQL language(s) does this apply to?
  - BigQuery
- Which SQL Formatter version are you using? 
  - 12.2.0 (latest)

---

BigQuery supports named arguments in several functions.
https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-reference#named_arguments

Named arguments are sometimes used in [JSON functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#double_for_json) and [Geography functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions).

Reading at the PostgreSQL implementation, it is not difficult to just add it to operators, so I'll try to PR it.
If the operator should work only in the function call, reject it.

**Comment by nene** [comment]
Thanks for the PR. I've release sql-formatter 12.2.1 with the fix. 💯
