### ISSUE TITLE
Feature Request: Be able to format all `.sql` file within a folder or with `.sql` extension

### ISSUE THREAD

**Issue by charnould** [sql-formatter-org/sql-formatter#612]
First, thanks for making this module and CLI!

**Describe the Feature**
Be able to format all `.sql` file within a folder or with `.sql` extension.
e.g.: `npx sql-formatter --fix some/folder/*`

**Why do you want this feature?**
At this time, it seems impossible to do so.
It would make `sql-formatter` a kind of `Prettier` for SQL (without relying on `Prettier`).

**Comment by nene** [comment]
Thanks for the feature request.

So far this hasn't been implemented because it can be easily accomplished with external tooling. For example:

- basic shell tools to execute the formatter on a group of files (e.g. using the `find` command)
- using it through a prettier plugin (prettier-plugin-sql)

I'm unlikely to spend time implementing this. But I'm open to pull requests, if somebody really wants this feature.

**Comment by charnould** [comment]
Indeed, `prettier-plugin-sql` works well.

**Comment by sd-eemilk** [comment]
@charnould How do you use the configs of `sql-formatter` with `prettier-plugin-sql`?

**Comment by charnould** [comment]
> @charnould How do you use the configs of `sql-formatter` with `prettier-plugin-sql`?

Below a simplified excerpt of my `package.json`.
I have no specific configs; I just want my code to be formatted.

```
{
  "dependencies": {
    "sql-formatter": "^12.2.4",
    "@typescript-eslint/eslint-plugin": "^6.2.0",
    "eslint-plugin-perfectionist": "^1.5.1",
    "@typescript-eslint/parser": "^6.2.0",
    "prettier-plugin-sql": "^0.15.1",
    "prettier": "^3.0.0",
  },
  "prettier": {
    "trailingComma": "none",
    "singleQuote": true,
    "printWidth": 120,
    "semi": false
  },
  "eslintConfig": {
    "env": {
      "browser": true,
      "es2024": true
    },
    "extends": [
      "plugin:@typescript-eslint/recommended-type-checked",
      "plugin:@typescript-eslint/stylistic-type-checked",
      "plugin:perfectionist/recommended-line-length",
      "eslint:recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "@typescript-eslint"
    ],
  }
}
```
