### ISSUE TITLE
Feature Request: Be able to store config inside package.json

### ISSUE THREAD

**Issue by charnould** [sql-formatter-org/sql-formatter#613]
Thanks again for making this package!

**Describe the Feature**
At this time, a custom `config` could not (I think) be passed though `CLI`. You can only pass a `config` path (pointing to a JSON file). Why not parsed `package.json` and look for a `sql-formatter` key with config?

**Why do you want this feature?**
Convenience, simplicity + not having another config file...

Ex:

```
{
  "module": "index.ts",
  "type": "module",
  "scripts": {
    "format:sql": "npx sql-formatter  --fix some/folder/users.sql",
  },
  "devdependencies": {
    "sql-formatter": "^12.2.2",
  },
  "sql-formatter": {
    "language": "sqlite",
    "tabWidth": 3,
    "linesBetweenQueries": 3,
    "keywordCase": "upper",
    "indentStyle": "tabularLeft" 
  },
```

**Comment by nene** [comment]
Thanks again for the feature requests.

That's one of these features which on the surface seem almost trivial, but when you start digging into it, there's lots of questions to ponder:

- how to locate this `package.json` file?
- if there's no package.json in the current dir, should it look up through dir hierarchy?
- if the package.json file doesn't contain an entry for sql-formatter, should one look for the next package.json upwards in dir hierarchy?

Much simpler to leave the answering of these questions to external tools, like using the formatter through a Prettier plugin, and letting Prettier handle all these concerns.

Therefore it's a feature which, although would be nice to have, is unlikely to be implemented.

**Comment by charnould** [comment]
Got it. Is there a prettier plugin? Thanks.
