### ISSUE TITLE
Feature Request: Optionally don't line break on short IF or CASE WHEN statements

### ISSUE THREAD

**Issue by pepsakdoek** [sql-formatter-org/sql-formatter#616]
**Describe the Feature**
For short IF statements (I guess shorter than the Expression width setting) keep it one a single line

**Why do you want this feature?**
Using 5 lines for this short IF is more than I think should be used:

`IF( full_carton_ind = "Y", "Full Carton", "Voice Picking" ) line_type,`

vs

```
          IF(
          full_carton_ind = "Y",
          "Full Carton",
          "Voice Picking"
          ) line_type,
```

**Comment by nene** [comment]
This should already work, except that this parenthesized expression:

```
(full_carton_ind = "Y", "Full Carton", "Voice Picking")
```

has a length of 56 characters, which is longer than the default `expressionWidth: 50`.

**Comment by pepsakdoek** [comment]
Ah, It works, on that query, but I have a longer CASE WHEN, but... I think CASE WHEN is probably wordy enough to keep behaviour as it currently is.
