### ISSUE TITLE
[FORMATTING] Issue with formatting Jinja templates

### ISSUE THREAD

**Issue by pranavajk1** [sql-formatter-org/sql-formatter#617]
**Input data**
The formatting is not correct when using Jinja Templates.
```sql
{{config(materialized = 'table')}}
```

**Expected Output**

```sql
{{ config(materialized = 'table') }}
```

**Actual Output**

```sql
{ { config(materialized = 'table') } }
```

**Usage**

- How are you calling / using the library?
- What SQL language(s) does this apply to?
- Jinja Templates
- Which SQL Formatter version are you using?
- 2.3.3

**Comment by nene** [comment]
In general, various template languages are not supported. But there exists a workaround. See #617
