### ISSUE TITLE
[VSCODE] published v1.6.0 doesn't have paramTypes

### ISSUE THREAD

**Issue by AndrewRocky** [sql-formatter-org/sql-formatter#622]
**Describe the bug**
Prettier-SQL.paramTypes is missing from both VSCode's marketplace's details page and settings. Version v1.6.0 (both installed and on Marketplace)

**To Reproduce**

Marketplace:
1. Go to Extension's [Marketplace page](https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode)
3. Scroll down to Configuration
4. There is no 'Prettier-SQL.paramTypes' option

Settings:
1. Go to .vscode/settings.json
2. Add     
```
    "Prettier-SQL.paramTypes": {
        "custom": [{ "regex": "\\{[a-zA-Z0-9_]+\\}" }],
    },
```
3. Get a 'Unknown Configuration Setting' message.

**Expected behavior**
1. 'Prettier-SQL.paramTypes' existing on [Marketplace page](https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode)
2. `"Prettier-SQL.paramTypes"` option being recognized in settings.json

**Screenshots**
settings.json:
![image](https://github.com/sql-formatter-org/sql-formatter/assets/79256277/e4493ff5-e227-474c-b4a9-659c9bdd5a33)

Extension's details page on Marketplace:
![image](https://github.com/sql-formatter-org/sql-formatter/assets/79256277/f51b096f-671b-43ae-8ba2-93aa3df8f158)

**Usage**

- What SQL language(s) does this apply to? - Probably all
- What VSCode version are you using? - 1.80.0
- What are your currently configured VSCode settings for the `prettier-sql` extension, if relevant to the issue?:
```
    "Prettier-SQL.expressionWidth": 140,
    "Prettier-SQL.tabulateAlias": true,
    "Prettier-SQL.paramTypes": {
        "custom": [{ "regex": "\\{[a-zA-Z0-9_]+\\}" }],
    },
```

**Additional context**
This is sad

**Comment by nene** [comment]
It's indeed sad that there hasn't been a release of the VSCode plugin since 15th Februrary 2023.

@inferrinizzard, who owns the plugin in VSCode marketplace, has not been releasing it and he hasn't responded to any pull requests to the plugin repository. I have postponed creating a new plugin in VSCode marketplace to replace it, as I really wouldn't like to do it, but I think there isn't much else I can do.

**Comment by nene** [comment]
I'm happy to report that finally there's a new extension is Visual Studio Marketplace: [SQL Formatter VSCode](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc)

It's a successor of the old "Prettier SQL VSCode" extension.
