### ISSUE TITLE
Feature Request: `pspl` (Postgres) Support

### ISSUE THREAD

**Issue by klondikemarlen** [sql-formatter-org/sql-formatter#623]
# Description of Feature

I would love to see support for `psql` commands under the `postgresql` language umbrella. Currently if I attempt to format a file with the `psql` command `\gexec` in it I get this error `Error: Parse error: Unexpected "\gexec`.

See https://www.postgresql.org/docs/current/app-psql.html -> `\gexec`

# Reasoning Behind Suggesting This Feature

As postgres support meta-programming of the form
```
SELECT my_custom_function_that_generates_an_sql_query(
    'some_arg1',
   'some_arg2',
   'etc_arg3'
)
\gexec
```
I would love to be able to format a file that has this kind of code in it.

One can run these scripts the traditional way via
```bash
psql "<connection-string>" --file ./my-script.sql
```

I have no idea how much work support for this might entail, so please forgive the presumption :)

**Comment by nene** [comment]
Thanks for the feature request, but currently I've halted any new feature developments on this tool.

I wouldn't say it's out of scope, but there are too many issues that this library has with formatting plain SQL, so including support for more than that is just not really feasible for now.

I also need to cut down on open feature requests. So, thanks for your interest, but I'm closing this.
