### ISSUE TITLE
Parsing of Postgres array slice operator throw error

### ISSUE THREAD

**Issue by wirekang** [sql-formatter-org/sql-formatter#624]
**Input data**

```sql
select (array_agg("test"))[:5] as "test" from "user"
```

**Actual Output**

```
Parse error: Unexpected ":5] as "te" at line 1 column 28```
```
**Usage**

- How are you calling / using the library?
https://github.com/wirekang/kysely-playground/issues/11

- What SQL language(s) does this apply to?
Postgres

- Which SQL Formatter version are you using?
12.2.0, 12.2.3

**Comment by nene** [comment]
Thanks for reporting. That's definitely a bug in the parser.

**Comment by wirekang** [comment]
I'm wondering how this issue can be solved. It seems that single parser handles all dialect.

**Comment by nene** [comment]
You're correct @wirekang. The formatter has a very rudimentary parser which is used for all dialects. There are some options passed to the lexer to define which dialect supports which keywords and operators.

So a simple way to fix this error is to add `:` to the list of Postgres operators. Additionally should add it to `formatOptions.alwaysDenseOperators`, so it won't be formatted with spaces around it.

Unfortunately there's also a bug with parenthesis formatting, so we'd end up with the following:

```sql
select
  (array_agg("test")) [:5] as "test"
from
  "user"
```

But definitely better than crashing :)
