### ISSUE TITLE
[FORMATTING] Inner SQL don't format when using $$

### ISSUE THREAD

**Issue by lucca65** [sql-formatter-org/sql-formatter#626]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT
  is_empty (
    $$ update tasks set score = 4 where score = 5 returning 1 $$
  , 'admins cannot update tasks in organizations that they are not admins'
  );
```

**Expected Output**

```sql
SELECT
  is_empty (
    $$ UPDATE tasks SET score = 4 WHERE score = 5 RETURNING 1 $$
  , 'admins cannot update tasks in organizations that they are not admins'
  );
```

**Actual Output**

```sql
SELECT
  is_empty (
    $$ update tasks set score = 4 where score = 5 returning 1 $$
  , 'admins cannot update tasks in organizations that they are not admins'
  );
```

**Usage**

- How are you calling / using the library?
  - I'm using it with Prettier. 
  - This is my config: 
 ```js
language: 'postgresql',
keywordCase: 'upper',
expressionWidth: 50,
commaPosition: 'before',
```

- What SQL language(s) does this apply to?
  - postgresql
- Which SQL Formatter version are you using?

**Comment by nene** [comment]
This is by design. The formatter has no way of knowing that this particular dollar-quoted string is SQL and should also be formatted.
