### ISSUE TITLE
sqlserver funtion format incorrect

### ISSUE THREAD

**Issue by zundaren** [sql-formatter-org/sql-formatter#628]
**Input data**

Which SQL and options did you provide as input?

```sql
CREATE FUNCTION testx.t2(@ProductID varchar, @ProductID3 varchar, @ProductID2 int)
    RETURNS varchar
AS

BEGIN
    DECLARE @ret int;
    SELECT @ret = '2'
    FROM testx.table1
    WHERE id = @ProductID2 and name = @ProductID and name = @ProductID3

    IF (@ret IS NULL)
        SET @ret = '';
    RETURN @ret;
END;
```

**Expected Output**

```sql
CREATE
FUNCTION testx.t2 (
  @ProductID varchar,
  @ProductID3 varchar,
  @ProductID2 int
) RETURNS varchar AS
 BEGIN
 DECLARE @ret int;
SELECT
  @ret = '2'
FROM
  testx.table1
WHERE
  id = @ProductID2
  and name = @ProductID
  and name = @ProductID3 
IF (@ret IS NULL)
    SET @ret = '';
RETURN @ret;
END;
```

**Actual Output**

```sql
CREATE
FUNCTION testx.t2 (
  @ProductID varchar,
  @ProductID3 varchar,
  @ProductID2 int
) RETURNS varchar AS BEGIN DECLARE @ret int;

SELECT
  @ret = '2'
FROM
  testx.table1
WHERE
  id = @ProductID2
  and name = @ProductID
  and name = @ProductID3 IF (@ret IS NULL)
SET
  @ret = '';

RETURN @ret;

END;
```

**Usage**

- How are you calling / using the library? 
-  12.2.4
- What SQL language(s) does this apply to? 
- sqlserver
- Which SQL Formatter version are you using? 
- transactsql

**Comment by nene** [comment]
As mentioned in README:

> It does not support:
> - Stored procedures.

Currently SQL Formatter looks at each `;`-delimited expression in isolation. It doesn't understand that between BEGIN ... END additional SQL statements can be nested. This is a fundamental problem with the way SQL Formatter is implemented and there's really no simple fix for it :(

I have started a work on [another SQL formatting library](https://github.com/nene/prettier-plugin-sql-cst), which addresses these shortcomings, but for now it doesn't yet support Transact-SQL, and likely won't in any near future as the Transact-SQL documentation is pretty damn confusing to understand and I personally have zero experience with it, plus I have other SQL dialects, like Postgres, which I'd like to have supported first. And well... even supporting Postgres will likely be many months of full-time work.
