### ISSUE TITLE
Feature request: Compact formatting for subqueries in expressions

### ISSUE THREAD

**Issue by infogulch** [sql-formatter-org/sql-formatter#631]
It would be nice if queries within expressions could be written compactly, perhaps inline, if the query is short enough.

I think this change would make sql more readable for those cases where a short query is used in expression context. I would expect this to depend on the length of the query and the Expression Width setting; if the query doesn't fit inline then it should fall back to the current formatting strategy.

This query, formatted with the current sqlite dialect, doubles the number of lines for the subquery:

```sql
UPDATE fetch
SET
    added_count = added_count + CHANGES()
WHERE
    id = (
        SELECT
            MAX(id)
        FROM
            fetch
    );
```

Where I would prefer:

```sql
UPDATE fetch
SET
    added_count = added_count + CHANGES()
WHERE
    id = (SELECT MAX(id) FROM fetch);
```

Another example, current formatting:

```sql
INSERT INTO
    item (feed_id, fetch_id, data)
SELECT
    feed_id
  , (
        SELECT
            MAX(id)
        FROM
            fetch
    ) AS fetch_id
  , JSON_EACH.value AS data
FROM
    NEW
  , JSON_EACH(NEW.data, "$.feed.items")
WHERE
    JSON_EACH.value ->> "$.guid" NOT IN (
        SELECT
            guid
        FROM
            item
        WHERE
            feed_id = NEW.feed_id
    );
```

My preference:

```sql
INSERT INTO
    item (feed_id, fetch_id, data)
SELECT
    feed_id
  , (SELECT MAX(id) FROM fetch) AS fetch_id
  , JSON_EACH.value AS data
FROM
    NEW
  , JSON_EACH(NEW.data, "$.feed.items")
WHERE
    JSON_EACH.value ->> "$.guid" NOT IN (SELECT guid FROM item WHERE feed_id = NEW.feed_id);    -- depending on the Expression Width setting
```

I drew these are examples from a project I'm working on now so they are somewhat similar to each other, but I have used expression subqueries fairly frequently (say, 2-10% of queries, off the top of my head) across several engines.

Maybe related: #360

**Comment by nene** [comment]
You might be interested in trying out a [new SQL formatting plugin for Prettier](https://github.com/nene/prettier-plugin-sql-cst) that I've written, which pretty much does what you're describing. This sort of variable-length expression formatting is really at the core of the [Prettier formatting algorithm.](http://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf)

I'm not planning to do any new feature development on SQL Formatter and instead concentrate on the aforementioned Prettier plugin which already does a much better job of formatting SQL. Its only drawback is the lack of supported SQL dialects.

**Comment by infogulch** [comment]
Ok thank you for summarizing the current development status.

I tried the online formatter, and I already like it better than this one, but it still doesn't inline as much as I would like:

<details>
<summary>Expand for comparison</summary>

sql-formatter:
```
CREATE TRIGGER ingest_fetch INSTEAD OF INSERT ON ingest FOR EACH ROW BEGIN
INSERT INTO
    fetch (feed_id, data, added_count)
SELECT
    feed_id
  , JSON_REMOVE(data, "$.feed.items") AS data
  , 0 AS added_count
FROM
    NEW;

INSERT INTO
    item (feed_id, fetch_id, data)
SELECT
    feed_id
  , (
        SELECT
            MAX(id)
        FROM
            fetch
    ) AS fetch_id
  , JSON_EACH.value AS data
FROM
    NEW
  , JSON_EACH(NEW.data, "$.feed.items")
WHERE
    JSON_EACH.value ->> "$.guid" NOT IN (
        SELECT
            guid
        FROM
            item
        WHERE
            feed_id = NEW.feed_id
    );

UPDATE fetch
SET
    added_count = added_count + CHANGES()
WHERE
    id = (
        SELECT
            MAX(id)
        FROM
            fetch
    );

END;
```

prettier-plugin-sql-cst:
```
CREATE TRIGGER ingest_fetch
INSTEAD OF INSERT ON ingest
FOR EACH ROW
BEGIN
  INSERT INTO fetch
    (feed_id, data, added_count)
  SELECT
    feed_id,
    JSON_REMOVE(data, "$.feed.items") AS data,
    0 AS added_count
  FROM NEW;

  INSERT INTO item
    (feed_id, fetch_id, data)
  SELECT
    feed_id,
    (
      SELECT
        MAX(id)
      FROM fetch
    ) AS fetch_id,
    JSON_EACH.value AS data
  FROM
    NEW,
    JSON_EACH(NEW.data, "$.feed.items")
  WHERE
    JSON_EACH.value ->> "$.guid" NOT IN (
      SELECT
        guid
      FROM item
      WHERE feed_id = NEW.feed_id
    );

  UPDATE fetch
  SET added_count = added_count + CHANGES()
  WHERE
    id = (
      SELECT
        MAX(id)
      FROM fetch
    );
END;
```

</details>

What do you think? Should I open a new issue on the `prettier-plugin-sql-cst` to make the same improvement?

Is the new formatter available as a vscode extension?

**Comment by nene** [comment]
> but it still doesn't inline as much as I would like

Perhaps you could give a concrete example. One feature/quirk of that plugin is that it also preserves some formatting of the original code. For example, if you give it:

```sql
UPDATE fetch
SET
    added_count = added_count + CHANGES()
WHERE
    id = (SELECT MAX(id) FROM fetch);
```

it will output:

```sql
UPDATE fetch
SET added_count = added_count + CHANGES()
WHERE id = (SELECT MAX(id) FROM fetch);
```

But if you give it the same query with the subquery also indented:

```sql
UPDATE fetch
SET
    added_count = added_count + CHANGES()
WHERE
    id = (
        SELECT
            MAX(id)
        FROM
            fetch
    );
```

It'll try to preserve the intent of indenting the subquery and will output the following:

```sql
UPDATE fetch
SET added_count = added_count + CHANGES()
WHERE
  id = (
    SELECT
      MAX(id)
    FROM fetch
  );
```

> Is the new formatter available as a vscode extension?

Not directly. You can install a Prettier extension and then install Prettier and this plugin for Prettier.

**Comment by infogulch** [comment]
> Perhaps you could give a concrete example.

I included a concrete example in the collapsed details section in my comment above, sorry if that was not clear.

That said, after reducing the wrapping manually it does do what I want. Thanks for indicating that I should watch out for preserved original formatting.

> You can install a Prettier extension and then install Prettier and this plugin for Prettier.

Oh ok, that should be fine. It's not super clear how to enable plugins at the moment, but I'll look into it.

Thank you for your attention!

**Comment by infogulch** [comment]
After a couple hours I give up on trying to configure prettier to work on my setup. Maybe I'll just format via the playground.
