### ISSUE TITLE
Format Procedures and Functions

### ISSUE THREAD

**Issue by Sayantansinharay451** [sql-formatter-org/sql-formatter#635]
**Unable to format Procedures and Functions**
I was writing a trigger then I noticed that it was not able to format it and threw an error.

After the error is thrown it does not format any other code

**Comment by nene** [comment]
As mentioned in the readme, the formatting of stored procedures is not supported.

Supporting this is not really feasible with the current architecture of the formatter. Also, various SQL dialects have different syntax for the procedures and this feature request does not mention an SQL dialect.
