### ISSUE TITLE
Feature Request: Config option to show parse chain

### ISSUE THREAD

**Issue by greg-finley** [sql-formatter-org/sql-formatter#637]
**Describe the Feature**
If we have a parsing error, you get a stack trace like this:
```
● SqlFormatter › formats BETWEEN within CASE

    Parse error at token: BETWEEN at line 4 column 20
    Unexpected BETWEEN token: {"type":"BETWEEN","raw":"BETWEEN","text":"BETWEEN","start":46,"precedingWhitespace":" "}. Instead, I was expecting to see one of the following:

    A DOT token based on:
        property_access → expression _ ● %DOT _ property_access$subexpression$1
        asteriskless_andless_expression$subexpression$1 →  ● property_access
        asteriskless_andless_expression →  ● asteriskless_andless_expression$subexpression$1
        andless_expression$subexpression$1 →  ● asteriskless_andless_expression
        andless_expression →  ● andless_expression$subexpression$1
        expression$subexpression$1 →  ● andless_expression
        expression →  ● expression$subexpression$1
        expression_with_comments_ →  ● expression _
        expression_chain_$ebnf$1 →  ● expression_with_comments_
        expression_chain_ →  ● expression_chain_$ebnf$1
        case_clause → %WHEN _ ● expression_chain_ %THEN _ expression_chain_
        case_expression$ebnf$2 → case_expression$ebnf$2 ● case_clause
        case_expression → %CASE _ case_expression$ebnf$1 ● case_expression$ebnf$2 %END
        asteriskless_andless_expression$subexpression$1 →  ● case_expression
        asteriskless_andless_expression →  ● asteriskless_andless_expression$subexpression$1
        asteriskless_free_form_sql$subexpression$1 →  ● asteriskless_andless_expression
        asteriskless_free_form_sql →  ● asteriskless_free_form_sql$subexpression$1
        select_clause$subexpression$1 →  ● asteriskless_free_form_sql select_clause$subexpression$1$ebnf$2
        select_clause → %RESERVED_SELECT ● select_clause$subexpression$1
        clause$subexpression$1 →  ● select_clause
        clause →  ● clause$subexpression$1
        expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause
        expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2
        statement →  ● expressions_or_clauses statement$subexpression$1
        main$ebnf$1 → main$ebnf$1 ● statement
        main →  ● main$ebnf$1
    A LINE_COMMENT token based on:
...
```

It would be cool to be able to give a config option to `format` to print the parse chain for any query, successful or not.

In the Python ecosystem, SQLFluff does this (i.e., the test suites turns [a SQL query](https://github.com/sqlfluff/sqlfluff/blob/b85f1ad0efadde210f60ea0f3d6b1b85b4c5c3e3/test/fixtures/dialects/snowflake/alter_table_column.sql#L3) into [its parsing output](https://github.com/sqlfluff/sqlfluff/blob/b85f1ad0efadde210f60ea0f3d6b1b85b4c5c3e3/test/fixtures/dialects/snowflake/alter_table_column.yml#L9-L21)).

**Why do you want this feature?**
Makes it easier to understand what `grammar.ne` is doing and debug potential issues.

**Comment by nene** [comment]
Well, a chain only makes sense in the context of an error, when the parsing stops at some token. Perhaps you meant showing a parse tree?

Anyway, implementing this would be a whole big feature on its own. I have pretty much stopped doing any new feature development on sql-formatter, so I'm very unlikely to implement such a feature. Especially as its use case is in the would-be-nice territory. If you really-really want such a feature, I'm open to pull requests. But I'm not convinced such a feature would actually find much use. Like, I personally find it usually pretty easy to diagnose the bugs that get reported. A whole lot of them are a result of some of the fundamental problems in the parser that can't really be easily fixed.

**Comment by nene** [comment]
I'm instead mainly concentrating on working on another SQL formatting tool [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst), which also involves writing a full [SQL parser](https://github.com/nene/sql-parser-cst). From that you do get a full syntax tree as an output, if that's something that interests you.

**Comment by greg-finley** [comment]
Thanks for the response! It makes sense. I'll close this for now but maybe give it a shot if I try to resolve some issues and find this useful.
