### ISSUE TITLE
[FORMATTING] Must disable error on parsing unexpected tokens

### ISSUE THREAD

**Issue by msbragi** [sql-formatter-org/sql-formatter#645]
Hello sir, very good job, but i can't use in my angular project.
My application let users to write query with custom tokens that my parser replace at runtime before execute.
For example the condition 
**{{ AND c.created >= $[rng_from] }}**
this means that if the param  $[rng_from] (optional during the user input) has value
become 
AND created >= "user input value"
else completely removed from the statement and so on for the others

At this time when i try to format the statements sql-formatter gives me an error when encounters the firs **{**
Is it possible to do?
TIA

I have seen on stackblitz an example that works, but with an older version of sql-formatter
https://stackblitz.com/edit/angular-ngf1xl?file=src%2Fapp%2Finput-overview-example.css

Original query:

`SELECT c.id, c.name AS label, c.id AS value, c.description, c.code AS codice, '#[COGNOME]' AS COGNOME, '&#129315; Ridi' AS ICONA FROM categories c WHERE 1=1 {{ AND c.created >= $[rng_from] }} {{ AND c.created <= $[rng_to] }} {{ AND 1 = #[IDUTENTE] }} ORDER BY 1`

Desired result:
------------------
```
SELECT
  c.id,
  c.name AS label,
  c.id AS value,
  c.description,
  c.code AS codice,
  '#[COGNOME]' AS COGNOME,
  '&#129315; Ridi' AS ICONA
FROM
  categories c
WHERE
  1 = 1 
  {{ AND c.created >= $[rng_from] }}
  {{ AND c.created <= $[rng_to] }}
  {{ AND 1 = #[IDUTENTE] }}
ORDER BY 1

**Comment by irazox** [comment]
I also experienced this issue. We have been using {{ parameter }} to insert our own parameter into SQL, but since version 10 this has been broken. We rolled back to version 9 where it does work, but we prefer to keep our packages up 2 date. 

Can you please look into this? Thanks!

![image](https://github.com/sql-formatter-org/sql-formatter/assets/51910111/ff84737f-2d7c-4002-a308-fe6a10eabc52)

**Comment by nene** [comment]
You can treat these placeholders as SQL parameters and define a custom parameter type for these. Like:

```json
{
  "paramTypes": {
    "custom": [{ "regex": "\\{\\{.+?\\}\\}" }]
  }
}
```

You can either save this to a config file (when running sql-formatter from command line) or pass this object as the second parameter of the `format()` function. 

The output will be like this, as the formatter has no idea about the meaning of these placeholders:

```sql
SELECT
  c.id,
  c.name AS label,
  c.id AS value,
  c.description,
  c.code AS codice,
  '#[COGNOME]' AS COGNOME,
  '&#129315; Ridi' AS ICONA
FROM
  categories c
WHERE
  1 = 1 {{ AND c.created >= $[rng_from] }} {{ AND c.created <= $[rng_to] }} {{ AND 1 = #[IDUTENTE] }}
ORDER BY
  1
```

- See the [custom paramTypes documentation](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/paramTypes.md#custom-parameter-syntax)
