### ISSUE TITLE
[FORMATTING] MS Access Query where column names have spaces

### ISSUE THREAD

**Issue by cjbarth** [sql-formatter-org/sql-formatter#646]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT 

TextLength_infor.Count,
LengthText_wm.Count,
Weight_infor.Count,
WeightText_wm.Count,
Image1.Count

FROM (SELECT COUNT([Length Text_infor]) AS Count FROM Assessment WHERE [Length Text_infor] <> "") AS TextLength_infor,
(SELECT COUNT([Length Text_wm]) AS Count FROM Assessment WHERE [Length Text_wm] <> "") AS LengthText_wm,
(SELECT COUNT([Weight_infor]) AS Count FROM Assessment WHERE [Weight_infor] <> "") AS Weight_infor,
(SELECT COUNT([Weight Text_wm]) AS Count FROM Assessment WHERE [Weight Text_wm] <> "") AS WeightText_wm,
(SELECT COUNT([Image 1]) AS Count FROM Assessment WHERE [Image 1] <> "") AS Image1

```

**Error**

```console
Unable to format SQL: Error: Parse error: Unexpected "[Length Te" at line 9 column 20
```

**Usage**

- How are you calling / using the library?
  - I'm using this library as part of the [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode), but am reporting here as this is decidedly a problem with token parsing related to the dialect of SQL.
  - I have no other SQL formatting tools installed, in fact, this is the first SQL anything that I've installed in VS Code.
  - I'm using the SQLFlavour of `sql` since there doesn't seem to be one that is related to MS Access SQL.
- What SQL language(s) does this apply to?
  - I'm working with a query in MS Access where spaces are allowed in column names if they are contained in brackets `[]`
- Which SQL Formatter version are you using?
  - I just installed from the Marketplace and the version appears to be listed as v1.6.0

**Comment by nene** [comment]
Although MS Access is not currently supported, treating it as Transact-SQL will most likely do the job.

Simply select "Transact-SQL" as the SQL dialect in extension settings. [See the FAQ](https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-)

Also, I suggest switching from the [prettier-sql-vscode](https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode) extension to [sql-formatter-vsc](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc) extension. The former is no longer maintained.

**Comment by cjbarth** [comment]
Indeed, using Transact SQL helped solve this problem. And thanks for the tip of the extension. I can't believe how many people are using the forked one and the deprecated on. I wonder if there is a way to help people find the correct one. You might consider putting a link to the VS Code extension at the top of your readme so that those that are coming here from the other extension will see that they have the wrong one.

Anyway, thanks for your help on this.
