### ISSUE TITLE
Feature Request: Config for uppercase / lowercase data types

### ISSUE THREAD

**Issue by karlhorky** [sql-formatter-org/sql-formatter#653]
**Describe the Feature**

Currently, using `keywordCase: 'upper'` results in 

```sql
CREATE TABLE
  users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(30) NOT NULL UNIQUE,
    password_hash VARCHAR(60) NOT NULL
  );
```

It would be nice to have an option (eg. `dataTypeCase`, could default to `keywordCase` value for backwards compatibility) to format the data types (`integer`, `varchar`, any other data types) as lowercase, since this is the style [in the PostgreSQL docs](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-EXAMPLES):

```sql
CREATE TABLE
  users (
    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username varchar(30) NOT NULL UNIQUE,
    password_hash varchar(60) NOT NULL
  );
```

**Why do you want this feature?**

This is the style [in the PostgreSQL docs](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-EXAMPLES).

**Comment by nene** [comment]
Yeah, makes sense. Especially as some SQL dialects treat data type names as keywords and others do not. Also, this would alleviate a general problem with the formatter not understanding the context where a keyword is used.

**Comment by nene** [comment]
Also relates to: #641

**Comment by karlhorky** [comment]
Potential alternative from https://github.com/sql-formatter-org/sql-formatter/issues/156#issuecomment-1826846259 would be an option `keywordCaseIgnore` (array), which would allow for more flexible customization:

> an option `keywordCaseIgnore` which is an array of any-case keywords to ignore when changing the case? Could be useful for multiple things, eg.
>
> ```js
> const options = {
>   language: 'postgresql',
>   keywordCase: 'upper',
>   keywordCaseIgnore: [
>     // Avoid changing case of `name` fields in tables
>     'name',
>     // Avoid changing case of data types
>     'varchar',
>     'integer',
>     // ...
>   ],
> }
> ```
