### ISSUE TITLE
[FORMATTING] MySQL format issue

### ISSUE THREAD

**Issue by DevRockstarZ** [sql-formatter-org/sql-formatter#657]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT *
FROM 
call
ORDER BY call.id;
```

**Expected Output**

```sql
SELECT
  *
FROM
  call
ORDER BY
  call.id;
```

**Actual Output**

```
Error: Parse error at token: . at line 4 column 14
Unexpected DOT token: {"type":"DOT","raw":".","text":".","start":33}. Instead, I was expecting to see one of the following:

A ASTERISK token based on:
    asterisk$subexpression$1 →  ● %ASTERISK
    asterisk →  ● asterisk$subexpression$1
    free_form_sql$subexpression$1 →  ● asterisk
    free_form_sql →  ● free_form_sql$subexpression$1
    other_clause$ebnf$1 → other_clause$ebnf$1 ● free_form_sql
    other_clause → %RESERVED_CLAUSE ● other_clause$ebnf$1
    clause$subexpression$1 →  ● other_clause
    clause →  ● clause$subexpression$1
    expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause
    expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2
    statement →  ● expressions_or_clauses statement$subexpression$1
    main$ebnf$1 → main$ebnf$1 ● statement
    main →  ● main$ebnf$1
```

**Notes**

When I tried below query, it also gives me wrong format.

* query
```sql
SELECT *
FROM 
call
```

* result
```
SELECT
  *
FROM
call << doesn't indent..!
```

- How are you calling / using the library? by using format(query,{options})
- What SQL language(s) does this apply to? mysql
- Which SQL Formatter version are you using? ^13.0.4

Thank you!

**Comment by nene** [comment]
The reason for this failure is `CALL` being a [reserved word in MySQL](https://dev.mysql.com/doc/refman/8.0/en/keywords.html). When I try to run the query in MySQL, I get an error:

> ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'call' at line 1

In short, this is not valid MySQL syntax.
