### ISSUE TITLE
[FORMATTING] The output of format  "SELECT now()"  is wrong

### ISSUE THREAD

**Issue by fanjinyu-fjy** [sql-formatter-org/sql-formatter#659]
**Input data**

Which SQL and options did you provide as input?

```sql
select now()
```

**Expected Output**

```sql
select
   now()
```

**Actual Output**

```sql
select
   now ()
```

**Usage**

- How are you calling / using the library?
- What SQL language(s) does this apply to?
    mySQL
- Which SQL Formatter version are you using?
    "sql-formatter": "^12.2.1",

**Comment by nene** [comment]
Please select "MySQL" as a dialect when formatting.
