### ISSUE TITLE
[FORMATTING] incorrect function/procedure named parameter syntax character formatting

### ISSUE THREAD

**Issue by m-tyler** [sql-formatter-org/sql-formatter#664]
**Input data**

Which SQL and options did you provide as input?
DB2 for IBM i version 7.3 (at least) through 7.5. 
The named parameter characters `=>` are split with a space between after formatting.

```sql
select * from table ( MySchema.MyFunction (Parm2 => 'Q*' ,Parm3 => 'Value*', Parm1 => 'Value' ,Parm5 => '*' ) )
```
![image](https://github.com/sql-formatter-org/sql-formatter/assets/1353665/7ba836f3-4e51-44b7-911a-386f15590c3e)

**Expected Output**

```sql
select
  *
from
  table (
    MySchema.MyFunction (
      Parm2 => 'Q*',
      Parm3 => 'Value*',
      Parm1 => 'Value',
      Parm5 => '*'
    )
  )
```

**Actual Output**

```sql
select
  *
from
  table (
    MySchema.MyFunction (
      Parm2 = > 'Q*',
      Parm3 = > 'Value*',
      Parm1 = > 'Value',
      Parm5 = > '*'
    )
  )
```
![image](https://github.com/sql-formatter-org/sql-formatter/assets/1353665/5e621f9d-f1a6-4a6b-a262-8b576bc70400)

**Usage**

- How are you calling / using the library? Right-Click -> Format Document With... -> Prettier SQL VSCode
- What SQL language(s) does this apply to? DB2 for IBM i 7.x
- Which SQL Formatter version are you using? 
![image](https://github.com/sql-formatter-org/sql-formatter/assets/1353665/cc7313ec-2282-4117-b176-0d55cfefc6ef)

**Comment by nene** [comment]
Thanks for reporting. The DB2i support is pretty rough around the edges at the moment.

Could you point me to DB2 documentation which mentions the support of this syntax? I haven't been able to locate one by myself.

I should also mention that this VSCode extension "Prettier SQL VSCode" does not have any DB2i support. And likely won't receive it, because it's no more maintained by its author. I suggest you instead use the official [SQL Formatter VSCode](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc) extension.

**Comment by m-tyler** [comment]
Procedure call: https://www.ibm.com/docs/en/i/7.1?topic=statements-call-statement

![image](https://github.com/sql-formatter-org/sql-formatter/assets/1353665/b1a93146-29c2-4ccf-9fc1-f4dc5ce8e542)


Function calls for scalar functions and table functions use the same parameter-name syntax.   The document reference is for 7.1.  

I don't any any knowledge about how many customers might be still at version 7.1 but at least using 7.1 as a starting point you can know if a feature is supported on which version.

**Comment by nene** [comment]
Thanks. Fixed now.

If you're interested in doing more, you might want to have a look at the list of operators [in the wiki](https://github.com/sql-formatter-org/sql-formatter/wiki/Operators) and see if it is missing something else for DB2i.
