### ISSUE TITLE
DROP TABLE [dbo].[name]; this sql formatting error

### ISSUE THREAD

**Issue by ni804160545** [sql-formatter-org/sql-formatter#666]
**Input data**

Which SQL and options did you provide as input?

```sql
DROP TABLE [dbo].[name];
```

**Expected Output**

```sql
Parse error: Unexpected "[dbo].[nam" at line 1 column 12
```

**Actual Output**

```sql
DROP TABLE [dbo].[name];
```

**Usage**

- How are you calling / using the library?
- What SQL language(s) does this apply to?
- Which SQL Formatter version are you using?

**Comment by ni804160545** [comment]
![Uploading Snipaste_2023-11-16_19-01-22.png…]()

**Comment by nene** [comment]
Please read the [FAQ](https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-).
