### ISSUE TITLE
Feature Request: Possibility to use tabs and comma position "before" in combination

### ISSUE THREAD

**Issue by saskiaeuler94** [sql-formatter-org/sql-formatter#667]
**Describe the Feature**
it is not possible to use "Comma Position = before" in combination with having tabs. When you have comma position before it is just possible to have spaces instead. I get the errormessage: "Unable to format SQL: Error: commaPosition: before does not work when tabs are used for indentation."

**Why do you want this feature?**
I prefer the comma at the beginning of the line because it makes it easier to debug the code. In my opinion this is clearer.
If you now have the option of working with tabs before the comma, the entire attribute is not shifted by two characters when commenting out. This keeps the code clearer as well.

**My suggestion**
Tabs if possible and otherwise fill with spaces. Example: First attribute has no comma, therefore insert tabs and two spaces instead.

Here ist an example:
status is:
SELECT
         id
--       , name --moved because of commenting out --> over a larger amount of code it becomes messy
       , vorname

desired status:
SELECT
         id
--    , name -- this attribut do not move because of commenting out
       , vorname

**Comment by nene** [comment]
Sorry, but this won't happen. The whole `commaPosition` feature is destined for removal in 14.0.0 because it's fundamentally broken.
