### ISSUE TITLE
[FORMATTING] DB2 for i allows special characters in column/table/schema names.

### ISSUE THREAD

**Issue by m-tyler** [sql-formatter-org/sql-formatter#668]
**Input data**
Working with an IBM DB2.
These special characters are allowed in column names, `@#$_`.  Current version of the format parser complains about strings that start with one of these characters but field names cannot begin with one of these special characters nor numbers, in DB2 for i.  

For the tests, add a special character to the schema and table names separately from the column names as the parser stops at the first item from left to right. 

```sql
select MY#FIELD from mylib.Table111 where MY#Field = 111111
```

**Expected Output**

```sql
select
  MY#FIELD
from
  mylib.Table111
where
  MY#ield = 111111
```

**Actual Output**
```
Unable to format SQL:
Error: Parse error: Unexpected "#FIELD fro" at line 1 column 10
```

**Usage**

- How are you calling / using the library? Using right-click or short-key.
- What SQL language(s) does this apply to? DB2 for i
- Which SQL Formatter version are you using? 1.6.0.

**Comment by nene** [comment]
Quoting from the [FAQ](https://github.com/sql-formatter-org/sql-formatter#im-having-a-problem-with-prettier-sql-vscode-extension):

> The [Prettier SQL VSCode](https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode) extension is no more maintained by its author.
>
> Please use the official [SQL Formatter VSCode](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc) extension to get the latest fixes from SQL Formatter library.
