### ISSUE TITLE
[VSCODE] Comma Position Setting Disappeared

### ISSUE THREAD

**Issue by lulufredo** [sql-formatter-org/sql-formatter#669]
**Describe the bug**
Comma Position setting disappeared (only have screenshot from Prettier SQL, but used to have it in SQL Formatter).

**To Reproduce**
Go to Extension Settings and search for Comma 

**Expected behavior**
Comma position setting to allow having commas before SELECT and GROUP BY clauses.

**Screenshots**
Option available in Prettier SQL:
![Screenshot 2023-11-21 at 16 35 42](https://github.com/sql-formatter-org/sql-formatter/assets/120529414/993194b7-eac6-4d8a-a37a-26b44b370290)

Option no longer available in SQL Formatter:
![Screenshot 2023-11-21 at 16 37 31](https://github.com/sql-formatter-org/sql-formatter/assets/120529414/37bbc7cb-b8c4-4fd1-92fc-25c439d3aa6f)

**Usage**

- What SQL language(s) does this apply to? All of them
- What VSCode version are you using? 

- Version: 1.84.2 (Universal)
- Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
- Date: 2023-11-09T10:52:33.687Z
- Electron: 25.9.2
- ElectronBuildId: 24603566
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Darwin arm64 22.6.0

- What are your currently configured VSCode settings for the SQL Formatter VSCode extension, if relevant to the issue?
No configuration available.

**Comment by nene** [comment]
The `commaPosition` setting has been intentionally removed in sql-formatter [14.0.0](https://github.com/sql-formatter-org/sql-formatter/releases/tag/v14.0.0) and accordingly in the SQL Formatter VSCode extension [3.0.0](https://github.com/sql-formatter-org/sql-formatter-vscode/blob/v3.0.0/CHANGELOG.md).

I notice though that the README of the VSCode extension still lists the two removed config options.

Will fix the README.

**Comment by nene** [comment]
Fixed in 3.0.1 of the VSCode extension.

**Comment by lulufredo** [comment]
Thanks so much for the quick reply—bummer, that was one of the most useful features for me. Is there any chance to request possibly a new implementation or something?

**Comment by nene** [comment]
I'm open for a PR with new implementation. The existing implementation was just one big unmaintainable hack, which is why it was removed.

**Comment by lulufredo** [comment]
Ah makes sense—thanks for clarifying!
