### ISSUE TITLE
[FORMATTING] sql-formatter crash on `grant` with `*`

### ISSUE THREAD

**Issue by eeeXun** [sql-formatter-org/sql-formatter#674]
**Input data**

Which SQL and options did you provide as input?

```sql
grant select, insert on *.* to u1;
```

**Expected Output**

```sql
grant
select
,
insert
  on *.* to u1;
```

**Actual Output**

> [!CAUTION]
> It crash!
> ```
> An Unexpected Error Occurred
> Parse error at token: . at line 1 column 26 Unexpected DOT token: {"type":"DOT","raw":".","text":".","start":25}. Instead, I was expecting to see one of the following: A ASTERISK token based on: asterisk$subexpression$1 → ● %ASTERISK asterisk → ● asterisk$subexpression$1 free_form_sql$subexpression$1 → ● asterisk free_form_sql → ● free_form_sql$subexpression$1 other_clause$ebnf$1 → other_clause$ebnf$1 ● free_form_sql other_clause → %RESERVED_CLAUSE ● other_clause$ebnf$1 clause$subexpression$1 → ● other_clause clause → ● clause$subexpression$1 expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2 statement → ● expressions_or_clauses statement$subexpression$1 main$ebnf$1 → main$ebnf$1 ● statement main → ● main$ebnf$1 A LINE_COMMENT token based on: comment → ● %LINE_COMMENT asteriskless_free_form_sql$subexpression$1 → ● comment asteriskless_free_form_sql → ● asteriskless_free_form_sql$subexpression$1 free_form_sql$subexpression$1 → ● asteriskless_free_form_sql free_form_sql → ● free_form_sql$subexpression$1 other_clause$ebnf$1 → other_clause$ebnf$1 ● free_form_sql other_clause → %RESERVED_CLAUSE ● other_clause$ebnf$1 clause$subexpression$1 → ● other_clause clause → ● clause$subexpression$1 expressions_or_clauses$ebnf$2 → expressions_or_clauses$ebnf$2 ● clause expressions_or_clauses → expressions_or_clauses$ebnf$1 ● expressions_or_clauses$ebnf$2 statement → ● expressions_or_clauses statement$subexpression$1 main$ebnf$1 → main$ebnf$1 ● statement main → ● main$ebnf$1 A BLOCK_COMMENT token based on: comment → ● %BLOCK_COMMENT asteriskless_free_form_sql$subexpression$1 → ●
> ```

**Usage**

- How are you calling / using the library?  `sql-formatter -l mysql file.sql`
- What SQL language(s) does this apply to? `mysql`
- Which SQL Formatter version are you using? `14.0.0`

**Comment by nene** [comment]
Looks like a bug. Thanks for reporting. 👍
