### ISSUE TITLE
[FORMATTING] sql-formatter crash on `create user` with `%`

### ISSUE THREAD

**Issue by eeeXun** [sql-formatter-org/sql-formatter#675]
**Input data**

Which SQL and options did you provide as input?

```sql
create user u1@% identified by 'passwd';
```

**Expected Output**

```sql
create user u1 @% identified by 'passwd';
```

**Actual Output**

> [!CAUTION]
> It crash!
> ```
> Error: Parse error: Unexpected "@% identif" at line 1 column 15.
> SQL dialect used: "mysql".
>     at mR.createParseError (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:193195)
>     at mR.tokenize (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:192981)
>     at yR.tokenize (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:194676)
>     at RA.tokenize (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:227313)
>     at RA.reset (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:199524)
>     at T.N.feed (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:4085)
>     at Object.parse (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:227468)
>     at oA.parse (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:227663)
>     at oA.format (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:227197)
>     at VA (https://unpkg.com/sql-formatter@latest/dist/sql-formatter.min.js:1:230203)
> ```

**Usage**

- How are you calling / using the library? `sql-formatter -l mysql file.sql`
- What SQL language(s) does this apply to? `mysql`
- Which SQL Formatter version are you using? `14.0.0`

**Comment by nene** [comment]
Thanks for reporting. Looks like another bug in parsing MySQL.

I'm not really sure how to best handle these special characters in user management related statements. I think these characters don't have any other meaning in different contexts. Possibly could treat @ as an operator.

**Comment by eeeXun** [comment]
Oops! My bad. And thank you!
