### ISSUE TITLE
Inserting white space at start of query

### ISSUE THREAD

**Issue by Minimistro32** [sql-formatter-org/sql-formatter#681]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT top 100 *
    FROM oa_tables
```

**Expected Output**

```sql
SELECT top 100 *
    FROM oa_tables
```

**Actual Output**

```sql
   SELECT top 100 *
     FROM oa_tables
```

**Usage**

- How are you calling / using the library?
  - vs code extension
- What SQL language(s) does this apply to?
  - pl/sql
- Which SQL Formatter version are you using?
  - 10.2.4

**Comment by nene** [comment]
SQL Formatter 10.x was released over a year ago. Please use the latest version.

I also don't know which VSCode extension you're using. There are several ones. See the README for link to officially supported extension.
