### ISSUE TITLE
Feature Request: Remove unnecessary parentheses

### ISSUE THREAD

**Issue by karlhorky** [sql-formatter-org/sql-formatter#684]
**Describe the Feature**

New default behavior in `sql-formatter` to remove unnecessary parentheses in SQL (maybe with a way to disable):

```sql
-- Before
SELECT
  sessions.id
FROM
  sessions
WHERE
  (
    (sessions.token = 'abc123')
    AND (sessions.user_id = 17)
    AND (sessions.expiry_timestamp > now())
  );

-- After
SELECT
  sessions.id
FROM
  sessions
WHERE
  sessions.token = 'abc123'
  AND sessions.user_id = 17
  AND sessions.expiry_timestamp > now();
```

**Why do you want this feature?**

Removing extra unnecessary parentheses can make code simpler and less nested

**Prior art**

Prettier does this:

![Screenshot 2023-12-05 at 12 24 44](https://github.com/sql-formatter-org/sql-formatter/assets/1935696/3e896557-bb2e-49e4-9bdc-75a5de463228)

Other projects also have had similar requests / implementation:

- https://github.com/dotnet/efcore/issues/28615
- https://github.com/dotnet/efcore/issues/26767
- https://github.com/dotnet/efcore/pull/30371

**Keywords for Search**

Operator precedence, operators, parenthesis

**Comment by nene** [comment]
This is pretty much out of scope for SQL Formatter. In the sense that implementing this would require proper parsing of SQL which SQL Formatter doesn't do.

Elimination of extra parenthesis is at least partly implemented by the `prettier-plugin-sql-cst`. Like converting `((a + b))` to `(a + b)`. I don't recall right now if I also implemented something else besides this most basic stuff.

I suggest you open this issue in `prettier-plugin-sql-cst`.

I'm closing this, as there's really no hope for it happening in SQL Formatter.

**Comment by karlhorky** [comment]
Ok thanks for the answer!

> I suggest you open this issue in `prettier-plugin-sql-cst`.

Duplicated issue open here:

- https://github.com/nene/prettier-plugin-sql-cst/issues/15
