### ISSUE TITLE
[FORMATTING] PostgreSQL `TYPE` keyword used as identifier causes indentation errors

### ISSUE THREAD

**Issue by karlhorky** [sql-formatter-org/sql-formatter#685]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT
  items.id,
  'project' AS type,
  items.created_at,
  items.modified_at
FROM
  items;
```

**Expected Output**

(no formatting change)

```sql
SELECT
  items.id,
  'project' AS type,
  items.created_at,
  items.modified_at
FROM
  items;
```

**Actual Output**

`TYPE` keyword causes subsequent lines to move down without indentation

```sql
SELECT
  items.id,
  'project' AS
type,
items.created_at,
items.modified_at
FROM
  items;
```

**Usage**

- How are you calling / using the library? [Website demo](https://sql-formatter-org.github.io/sql-formatter/)
- What SQL language(s) does this apply to? PostgreSQL
- Which SQL Formatter version are you using? 14.0.0

**Hypothesis**

Maybe [the `'[SET DATA] TYPE'` array item in `onelineClauses`](https://github.com/sql-formatter-org/sql-formatter/blob/d9db4ca27b5c8f210bd46e0e367962db1861698e/src/languages/postgresql/postgresql.formatter.ts#L54) or [the `'TYPE'` keyword](https://github.com/sql-formatter-org/sql-formatter/blob/d9db4ca27b5c8f210bd46e0e367962db1861698e/src/languages/postgresql/postgresql.keywords.ts#L387) have something to do with it

**Related issues**

- Potentially related to https://github.com/sql-formatter-org/sql-formatter/issues/302

**Comment by nene** [comment]
Indeed, this `[SET DATA] TYPE` rule is the cause of this. Probably best to drop support for the shorthand syntax and only detect `SET DATA TYPE`.

Another part is the `TYPE` keyword itself. This will affect the `keywordCase` option and is indeed essentially the same issue as #302
