### ISSUE TITLE
[FORMATTING] % modulo formatting causes parse error

### ISSUE THREAD

**Issue by avishj** [sql-formatter-org/sql-formatter#699]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT title FROM movies WHERE year % 2 = 0;
```

**Expected Output**

```sql
SELECT
    title 
FROM 
    movies 
WHERE 
    year % 2 = 0;
```

**Actual Output**

```sql
SELECT title FROM movies WHERE year % 2 = 0;
```
- It errors out: Unable to format SQL: Error: Parse error: Unexpected "% 2 = 0;"

**Usage**

- How are you calling / using the library?
- Called via Prettier SQL VSCode
- What SQL language(s) does this apply to?
- TSQL or any other which uses % for modulus operation in expressions.
- Which SQL Formatter version are you using?
- v1.6.0

**Comment by nene** [comment]
Simply configure the dialect as Transact-SQL. See the [FAQ](https://github.com/sql-formatter-org/sql-formatter#frequently-asked-questions).

Also, the Prettier SQL VSCode extension is no more maintained.
