### ISSUE TITLE
[Thread stuck]Cost a long time for formatting a 5000 lines of SQL statements

### ISSUE THREAD

**Issue by LauraXia123** [sql-formatter-org/sql-formatter#70]
When the SQL statements too long, it will cost too long time to format, about 10 seconds or more. Can be optimized for this?

**Comment by xiaoqingb** [comment]
when formatting, the page will be paused  a long time (2000+lines,  cost  more than 10s)
if the pc is cheap, the browser will collapse

**Comment by nene** [comment]
With the latest 7.0 release performance has gone up significantly.

At least I'm now able to format 15 000 lines of SQL in just under 2 seconds.
