### ISSUE TITLE
[FORMATTING] Postgres formatter throws error when '@?' operator is used for json filtering

### ISSUE THREAD

**Issue by tliao-varicent** [sql-formatter-org/sql-formatter#707]
**Input data**

Which SQL and options did you provide as input?

```sql
select * from foo_table where jsonCol @? '$.foo ? (@.foo == "foo")'
```

**Actual Output**

```sql
Error: Parse error: Unexpected "? '$.foo ? (@.foo == "foo")'
```

**Usage**

- How are you calling / using the library? `format(text, { language: 'postgresql' })`
- What SQL language(s) does this apply to? Postgres
- Which SQL Formatter version are you using? 15.1.2

**Comment by nene** [comment]
Sorry, but I'm unable to reproduce this bug. The `@?` operator is definitely supported for PostgreSQL.

I only managed to get an error message like this when I set the `language` option to `redshift`, `plsql` or `transactsql`. You can try it on [the demo page](https://sql-formatter-org.github.io/sql-formatter/).

**Comment by tliao-varicent** [comment]
thank you for investigating, what appears have happened was an error with my package.json set to the wrong version of sql-formatter
