### ISSUE TITLE
[FORMATTING] function name should not be changed in pgsql

### ISSUE THREAD

**Issue by thilllon** [sql-formatter-org/sql-formatter#710]
Hi, thanks for the great work.

`$function$` should not be changed after formatting the code below:

**Input data**

Which SQL and options did you provide as input?

```sql
-- original code

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;
```

**Expected Output**

```sql
CREATE
    OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql
    SECURITY DEFINER AS
$function$
begin
    insert into public.profiles (id, full_name, avatar_url)
    values (new.id,
            new.raw_user_meta_data ->> 'full_name',
            new.raw_user_meta_data ->> 'avatar_url');

    return new;
end;
$function$;

```

**Actual Output**

```sql

CREATE
OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $ function $ begin
-- Error occurs here `$ function $` 
insert into
  public.profiles (id, full_name, avatar_url)
values
  (
    new.id,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  );

return new;

end;

$ function $;
```

**Usage**

- How are you calling / using the library? [vscode extension](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc)
- What SQL language(s) does this apply to? pgsql
- Which SQL Formatter version are you using? `"sql-formatter": "^15.1.1"`

**Comment by nene** [comment]
Thanks for reporting, but I'm unable to reproduce this issue.

Make sure you have selected PostgreSQL as the SQL dialect you want to format: https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-

**Comment by thilllon** [comment]
My bad. It worked after setting this, `"SQL-Formatter-VSCode.dialect": "postgresql"`
Thanks!
