### ISSUE TITLE
Unable to configure to use the configuration setting for placeholders

### ISSUE THREAD

**Issue by mellasmpa** [sql-formatter-org/sql-formatter#712]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT * FROM receipts WHERE tin = {tin}
```

**Expected Output**

```sql
SELECT
    *
FROM
    receipts
WHERE
    tin = {tin}
```

**Actual Output**

```sql
Unable to format SQL: Error: Parse Error: Unexpected "{tin}"
```

**Usage**

- How are you calling / using the library?
- What SQL language(s) does this apply to?
- Which SQL Formatter version are you using?

When I save my  query it produces the above error with sqlite. The version I am running is 4.0.3

**Comment by nene** [comment]
I suspect you're using SQL Formatter VSCode version 4.0.2 (not the 4.0.3 from the future).

You say that you're unable to configure it to understand these `{..}` placeholder. Could you please provide the configuration options you are using? In particular, what have you configured as the value of [SQL-Formatter-VSCode.paramTypes](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/paramTypes.md).

**Comment by mellasmpa** [comment]
Kindly find bellow my configurations.

```code
  "SQL-Formatter-VSCode.paramTypes": {
    "placeholder": "{}"
  },
  "SQL-Formatter-VSCode.functionCase": "upper",
  "SQL-Formatter-VSCode.keywordCase": "upper",
  "SQL-Formatter-VSCode.ignoreTabSettings": true,
  "SQL-Formatter-VSCode.tabSizeOverride": 4,
  "SQL-Formatter-VSCode.dialect": "sqlite",
```

**Comment by mellasmpa** [comment]
Thank you for your support. I followed the instructions from the link provided above and it worked.

Thank you.
