### ISSUE TITLE
[FORMATTING] Why are tabularLeft parentheses so ugly? Can you add hierarchical styles or align backspace

### ISSUE THREAD

**Issue by Chasen-Zhang** [sql-formatter-org/sql-formatter#713]
![aRCI6zLwbs](https://github.com/sql-formatter-org/sql-formatter/assets/15354455/26b6ff30-95fc-4fc1-93da-94aed9f31e54)

**Comment by Chasen-Zhang** [comment]
> That's one of the reasons why [the tabular formatting styles](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/indentStyle.md) have been deprecated and will be removed in the next major release.

You mean just keep the standard model？

**Comment by nene** [comment]
yes.
