### ISSUE TITLE
Unable to use "#" in table names

### ISSUE THREAD

**Issue by progton1** [sql-formatter-org/sql-formatter#717]
**Describe the bug**
I'm working in a database that has some connecting tables that are defined like this:

`SOME_TABLE#SOMETHING `
The issue presents itself when the table has a pound sign in its name.

This causes the vscode plugin to generate the following error:
`Unable to format SQL: Error: Parse error: Unexpected "#SOMETHING" at line 2 column 16` 

**Expected behavior**
That the plugin would format the SQL script

**Actual behavior**
Recieved an error.

**Usage**

- How are you calling / using the library?
  I'm using the VSCode plugin and calling it with the usual formatting command (SHIFT + ALT + F)

- What SQL language(s) does this apply to?
  I'm assuming this applies to most dialects.

- Which SQL Formatter version are you using?
  v1.6.0

**Comment by nene** [comment]
First off, you seem to be using the "Prettier SQL VSCode" extension. This is no more maintained. See the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#im-having-a-problem-with-prettier-sql-vscode-extension).

> I'm assuming this applies to most dialects.

Not quite. Rather the opposite is true. Most SQL dialects do not allow `#` characters in table names (or any identifier names). I don't know which dialect this is that you are using.

**Comment by nene** [comment]
Not enough info to do anything about this. So I'm closing this.
