### ISSUE TITLE
Canot format document when '#' character is Found

### ISSUE THREAD

**Issue by pgmlloyd** [sql-formatter-org/sql-formatter#736]
**Describe the bug**
Document contains below SQL statement, along with other statements
```sql
select prac01, prastr, prainv,
       pramdl, prasr#,
       prara#, coalesce(xcxcol,0)
  from disk.pcrrap
  left join disk.xfrcxp
         on xcxptr = PRAC01
  where PRAC01 <> ' '
    and prasr#=' '
;        
```
**Expected behavior**
Formatted statement

**Actual behavior**
Error: Unable to format SQL: Error: Parse error: Unexpected "#, " at line 16 column 21

**Usage**

- How are you calling / using the library? F1>Format Document With...>Prettier  SQL VS Code
- What SQL language(s) does this apply to? DB2
- Which SQL Formatter version are you using? 1.6.0

**Comment by nene** [comment]
Please read the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#frequently-asked-questions).
