### ISSUE TITLE
[FORMATTING] array type

### ISSUE THREAD

**Issue by leelhn2345** [sql-formatter-org/sql-formatter#742]
**Describe the bug**

formatting error occurs when `[]` is in the code. 

```sql
create table projects (



id serial primary key not null,






subscriptions text[]


);

```
**Expected behavior**

expected the formatted output to be like below
```sql
create table projects (
  id serial primary key not null,
  subscriptions text[]
);
```

**Actual behavior**

i have the error 

```sh
Error: Parse error: Unexpected "[]
);"
```

my current alternative is 

```sql
create table projects (
  id serial primary key not null,
  subscriptions text array
);
```

**Usage**

- How are you calling / using the library?
via [conform.nvim](https://github.com/stevearc/conform.nvim)
- What SQL language(s) does this apply to?
postgresql
- Which SQL Formatter version are you using?
v15.3.1

**Comment by nene** [comment]
Just select the PostgreSQL dialect when formatting. Please read the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#parse-error-unexpected--at-line-).
