### ISSUE TITLE
[FORMATTING] Issue Title Here

### ISSUE THREAD

**Issue by Altonymous** [sql-formatter-org/sql-formatter#743]
**Input data**
SELECT webhook_data_json.unified_receipt.latest_receipt_info[0].is_trial_period::boolean

**Expected Output**

SQL to be formatted.

**Actual Output**

Unable to format SQL: Error: Parse error: Unexpected "[0].is_tri" at line 5 column 112

**Usage**

- How are you calling / using the library? VS Code Extension
- What SQL language(s) does this apply to? RedShift (Super DataType)
- Which SQL Formatter version are you using? sql-formatter v12.0.6 (Build into Prettier SQL VSCode extension.

**Comment by nene** [comment]
Thanks for reporting.

I didn't know that RedShift supports the array-access syntax. Could you point me to the relevant part of RedShift documentation that describes this?

Be aware though that I can't fix this issue in "Prettier SQL VSCode extension". See the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#im-having-a-problem-with-prettier-sql-vscode-extension).
