### ISSUE TITLE
[FORMATTING] Formatter doesn't like the ~ in SQL statement

### ISSUE THREAD

**Issue by zjpersc** [sql-formatter-org/sql-formatter#744]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT bar, foo FROM foo_bar WHERE customer_prefix_name ~ '^.*\\d{9}.*$' GROUP BY bar
```

**Expected Output**

```sql
SELECT
  bar,
  foo
FROM
  foo_bar
WHERE
  ~ customer_prefix_name '^.*\\d{9}.*$'
GROUP BY
  bar
```

**Actual Output**

```sql
Parse error: Unexpected "~ '^.*\\d{" at line 1 column 57.
This likely happens because you're using the default "sql" dialect.
If possible, please select a more specific dialect (like sqlite, postgresql, etc).
```

**Usage**

- How are you calling / using the library?
Included as part of a toolbox plugin for Backstage:
https://github.com/drodil/backstage-plugin-toolbox

- What SQL language(s) does this apply to?
Redshift

- Which SQL Formatter version are you using?
Tried w v13.1.0 and v15.3.1

**Comment by nene** [comment]
It works fine. Just select "redshift" dialect, not the default "sql" one, like the error message suggests to you. [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#parse-error-unexpected--at-line-).

I don't know how to do that in this [drodil/backstage-plugin-toolbox](https://github.com/drodil/backstage-plugin-toolbox), you'll need to figure this out on your own or ask from the developers of that plugin.
