### ISSUE TITLE
[FORMATTING] Will not format #Temp Tables

### ISSUE THREAD

**Issue by bharris6avera** [sql-formatter-org/sql-formatter#745]
**Input data**

Which SQL and options did you provide as input?

```sql
Select *
From #temp as A
left join table as B 
    on A.ID = B.ID
```

**Expected Output**

```sql
Select
    *
From
    #temp as A
    left join table as B on A.ID = B.ID
```

**Actual Output**

Unable to format SQL: Error: Parse error: Unexpected "#temp as A" at line 4 column 5

**Usage**

- How are you calling / using the library?
      Right click in the white space of the document and select "Format Document"
- What SQL language(s) does this apply to?
      T-SQL
- Which SQL Formatter version are you using?
      ["INFO" - 8:42:51 AM] Extension Name: esbenp.prettier-vscode.
      ["INFO" - 8:42:51 AM] Extension Version: 10.4.0.

**Comment by nene** [comment]
This works fine, but you have to select Transact-SQL as the SQL dialect that you're formatting.

I guess you're probably using this library through [prettier-plugin-sql](https://github.com/un-ts/prettier/tree/master/packages/sql). Just configure `dialect: 'transactsql'`
