### ISSUE TITLE
[FORMATTING] MariaDB function call parenthesis spacing results in invalid MariaDB SQL

### ISSUE THREAD

**Issue by theking2** [sql-formatter-org/sql-formatter#757]
**Input data**

Which SQL and options did you provide as input?

```sql
select
    group_concat(PHYSICIAN separator ' / ') Doktor
from
	invoice_physician
group by
    INVOICENR;
```

**Expected Output**

```sql
select
    group_concat(PHYSICIAN separator ' / ') Doktor
from
	invoice_physician
group by
    INVOICENR;
```

**Actual Output**

```sql
select
    group_concat (PHYSICIAN separator ' / ') Doktor
from
	invoice_physician
group by
    INVOICENR;
```

**Usage**

- VS Code 
- Currently using MariaDB 11.4.2
- v4.1.1

MariaDB does not like a space between `GROUP_CONCAT` and the `(`. Don't ask but using the formatter breaks my code here.

**Comment by theking2** [comment]
and ultimatelily here https://mariadb.com/kb/en/parentheses/

**Comment by nene** [comment]
You're saying that you're using version 4.1.1. I suppose you're referring to the version of the VS Code plugin.

According to my testing, this bug does not exist in SQL Formatter. You can try it on [the demo page](https://sql-formatter-org.github.io/sql-formatter/).

The most likely cause is that you haven't selected MariaDB as the SQL dialect that you're formatting. See the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#parse-error-unexpected--at-line-).

**Comment by nene** [comment]
I'm closing this. Feel free to comment if the above does not solve your issue.

**Comment by theking2** [comment]
I went to a number of SQL  formatters lately and had not specified MariaDB as dialect for this one. After adding this to `settings.json`

````js
    "SQL-Formatter-VSCode.dialect": "mariadb",
```

the problem went away. Thanks.
