### ISSUE TITLE
[FORMATTING] problem with line like 'ORDER BY t1.DATE DESC, t1.[%title%] ASC'

### ISSUE THREAD

**Issue by Aliaksandr3by** [sql-formatter-org/sql-formatter#767]
`ORDER BY t1.DATE DESC, t1.[%title%] ASC`

Unable to format SQL:
Error: Parse error: Unexpected "[%album ar" at line 5 column 18

**Comment by nene** [comment]
Please provide more details, like:

- Which SQL dialect are you using?
- What is this `[%title%]` syntax? I haven't seen such a thing before. Is it some sort of templating?

**Comment by nene** [comment]
In case this is templating syntax, please see the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#my-sql-contains-templating-syntax-which-sql-formatter-fails-to-parse)

**Comment by Aliaksandr3by** [comment]
I use foobar2000 + sql

![image](https://github.com/user-attachments/assets/1c094e9c-ca75-40a4-8ea1-4dee2ef65c91)

**Comment by nene** [comment]
So, you're using SQLite. But according to my knowledge this `[%title%]` thingie is not part of SQLite syntax.

I'm sure it's some sort of templating syntax. Please see the above FAQ link on how to deal with templating syntax.

PS. I have no idea if or how this foobar2000 intergates with SQL formatter.

**Comment by Aliaksandr3by** [comment]
the one is part of foobar2000  and foo_uie_sql_tree

![image](https://github.com/user-attachments/assets/c32c3651-12d8-469f-ab3b-72b1b8c619a8)

**Comment by nene** [comment]
This does not clarify things for me. Perhaps you should search for help from developers of this foobar2000.

**Comment by Aliaksandr3by** [comment]
I use VS code for SQL, but your program (extension) give to me the 
Error: Parse error: Unexpected "[%album ar" at line 5 column 18

I think you might solve it.
e.g.
npp + plugin good working with this code
![image](https://github.com/user-attachments/assets/12d72935-37b8-43e5-9607-93972590b34a)

**Comment by nene** [comment]
Aha... I realize now that SQLite actually also supports these `[...]` style quotes. However, so does SQL Formatter.

Looks like you haven't specified SQLite as the dialect that you're formatting.

Again. Please read the FAQ.
