### ISSUE TITLE
[FORMATTING] Can't handle array type

### ISSUE THREAD

**Issue by Mooli88** [sql-formatter-org/sql-formatter#777]
**Input data**

Which SQL and options did you provide as input?

```sql
CREATE TABLE public.todos (
  assigned_to UUID[] NOT NULL
);
```

**Expected Output**
No change or:
```sql
assigned_to UUID [] NOT NULL
```

**Actual Output**

Error: `Unable to format SQL: Error: Parse error: Unexpected "[] NOT NUL" at line 27 column 21`

**Usage**

- How are you calling / using the library? - *Vscode format document / Shift + Option + F*
- What SQL language(s) does this apply to? - *Postgres*
- Which SQL Formatter version are you using? - *v1.6.0*

**Comment by nene** [comment]
Please read the FAQ that you can find in the README. Your problem is solved
by correct configuration and by not using the outdated VSCode plugin.
