### ISSUE TITLE
Feature Request: Ignore unrecognized syntax and continue formatting the text

### ISSUE THREAD

**Issue by Silver-Fang** [sql-formatter-org/sql-formatter#782]
**Describe the Feature**
Provides an extension option to ignore unrecognized syntax instead of reporting an error.

**Why do you want this feature?**
I know that there are many common procedures syntax that the extension will not support in a short time. But can we ignore these unsupported syntax for a while, instead of just reporting an error and giving up formatting the whole text?

**Comment by mcmxcdev** [comment]
Well, users can write any kind of syntax and end up accidentally with a state that cannot get formatted and then encounter a breaking page. Both suggestions wouldn't help in that case, and I wasn't able to try/catch `formatDialect` on our end.

**Comment by nene** [comment]
> I wasn't able to try/catch formatDialect on our end.

Perhaps you can elaborate on that. For me it works just fine.

**Comment by mcmxcdev** [comment]
> Perhaps you can elaborate on that. For me it works just fine.

My bad, I messed up there and it works now! Being able to try/catch errors is good enough functionality for us.
