### ISSUE TITLE
[VSCode]: uuid_generate_v4() is not recognised as a function

### ISSUE THREAD

**Issue by mechastriker3** [sql-formatter-org/sql-formatter#798]
### Expected output
```sql
uuid_generate_v4()
```
### Actual output
```sql
uuid_generate_v4 ()
```

### Which SQL dialect does this apply to?

PostgreSQL

### Which SQL dialect is configured in your VSCode extension settings?

PostgreSQL

### Version of the VSCode extension

v4.1.3

### I have tried to reproduce this issue on the [demo page](https://sql-formatter-org.github.io/sql-formatter/), and it

- [X] Reproduces
- [ ] Does not reproduce

**Comment by nene** [comment]
This is pretty much the same issue as #444.

Unfortunately there is no easy fix for this.
