### ISSUE TITLE
Feature Request: Java module compatibility

### ISSUE THREAD

**Issue by Suomm** [sql-formatter-org/sql-formatter#800]
for details: https://github.com/conveyal/kryo-tools/issues/3

**Comment by nene** [comment]
Thanks for the feature request, but I have no idea what you're asking for.

I'm not planning to spend time to figure out what it is that you would like to have. Please take some effort to explain this or otherwise I'm just going to close this feature request.

**Comment by Suomm** [comment]
I sincerely apologize for the oversight. It escaped my attention that there is an existing project with an identical name. https://github.com/vertical-blank/sql-formatter

**Comment by nene** [comment]
That's pretty interesting info. Apparently that project is a Java port of this JavaScript library, which in turn is a port of a [PHP library](https://github.com/jdorn/sql-formatter).

**Comment by Suomm** [comment]
> That's pretty interesting info. Apparently that project is a Java port of this JavaScript library, which in turn is a port of a [PHP library](https://github.com/jdorn/sql-formatter).

都是非常不错的 SQL 格式化项目，收藏了。
