### ISSUE TITLE
Feature Request: Could the parser be exported on its own

### ISSUE THREAD

**Issue by tylersayshi** [sql-formatter-org/sql-formatter#802]
**Describe the Feature**
the formatter is great! and a super nice thing to have when editing sql strings in typescript.

What would be really nice is to have direct access to the parser without needing to run the formatter. Maybe this would be exported from a different exports field in the package.json like 

```ts
import {parser} from 'sql-formatter/parser';
```

but regardless of how it would be done, it seems like a really valuable piece of sql-formatter that would be good to expose.

**Why do you want this feature?**
We are building a sql query builder on my team and would like to test that we are building valid queries in a programmatic way.

We are specifically using clickhouse, so may be interested in contributing back with support for a clickhouse dialect later down the road, but for now the default dialect seems to be working for us through prettier-plugin-sql.

**Comment by nene** [comment]
Thanks for the feature request.

I have to however disappoint you in telling that SQL Formatter doesn't really use a proper parser. While a quick glance at the source code might hint like there is a parser, it's very-very rudimentary and with lots of problems. Well, really most of the problems with SQL Formatter come down to this deficiency of there not being a parser. Though on the other hand, not having a proper parser is the reason why the formatter is able to support so many SQL dialects.

However, if you are interested in a parser, I'm also slowly working on a follow-up project for SQL Formatter which does use a proper SQL parser. You might want to take a look at my [sql-parser-cst](https://github.com/nene/sql-parser-cst) repository and the related [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst). Especially for SELECT statements, that parser should work pretty well. Though it is still just a parser, not a validator, so it won't really tell you if it's a valid query. But it's definitely better than anything inside SQL Formatter.

So you'll have to excuse me as I'm going to close this feature request as I think exposing the "parser" that's inside SQL Formatter would do more harm than good.

**Comment by tylersayshi** [comment]
no worries on closing this, i'm still glad i asked. Thanks for the thorough explanation and  the suggestion!

`sql-parser-cst` looks like a really good fit for what we'd be looking for. 100% proper queries is less of a concern and we are more looking to catch typos along the lines of mismatched parentheses or bad characters.
