### ISSUE TITLE
Is this affiliated with prettier/prettier?

### ISSUE THREAD

**Issue by YLivay** [sql-formatter-org/sql-formatter#803]
Hello, I was wondering if this is officially affiliated with prettier/prettier.

**Comment by nene** [comment]
Short answer: no.

Long answer: There's no technical relationship with prettier. The only relationship is that there exists a prettier plugin for SQL which uses SQL Formatter internally. But it's really not a proper prettier plugin, it's just a thin wrapper around this library and doesn't make use of the prettier API to format the code.

**Comment by YLivay** [comment]
Thanks for the quick reply!
