### ISSUE TITLE
formatting issue fo sql server

### ISSUE THREAD

**Issue by mahdiyar021** [sql-formatter-org/sql-formatter#805]
**Input data**
`
IF OBJECT_ID(N'[DatanexMigrationTable]') IS NULL BEGIN    CREATE TABLE [DatanexMigrationTable] (        [MigrationId] nvarchar(150) NOT NULL,        [ProductVersion] nvarchar(32) NOT NULL,        CONSTRAINT [PK_DatanexMigrationTable] PRIMARY KEY ([MigrationId])    );END; BEGIN TRANSACTION; CREATE TABLE [ss] (    [Id] int NOT NULL IDENTITY,    [mae] nvarchar(max) NULL,    CONSTRAINT [PK_ss] PRIMARY KEY ([Id])); INSERT INTO [DatanexMigrationTable] ([MigrationId], [ProductVersion])VALUES (N'20241207180533_Wigucipiqixukawo', N'8.0.6'); COMMIT;`

Which SQL and options did you provide as input?
sql server

**Actual Output**
Error: Unsupported SQL dialect: SQL Server

**Comment by mahdiyar021** [comment]
sql will be execute but cant formating

**Comment by nene** [comment]
Well, the error says it all. The dialect named "SQL Server" is not supported. Use "transactsql" or "tsql" instead.

https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/language.md

**Comment by mahdiyar021** [comment]
totally my bad , tanx
