### ISSUE TITLE
For some dialects, SQL statements containing the `?` placeholder cannot be processed normally.

### ISSUE THREAD

**Issue by meiMingle** [sql-formatter-org/sql-formatter#806]
**Input data**

```javascript
sqlFormatter.format('SELECT * FROM tbl WHERE foo = ?', {
  language:'plsql',
  params: ["'bar'"]
})
```

**Expected Output**

```sql
select
  *
from
  table
where
  name like 'bar'
```

**Actual Output**

![image](https://github.com/user-attachments/assets/89379d32-7e55-41ee-9417-215c002a86a2)

> TokenizerEngine.ts:49 Uncaught Error: Parse error: Unexpected "?" at line 1 column 31.
SQL dialect used: "plsql".
    at HR.createParseError (TokenizerEngine.ts:61:12)
    at HR.tokenize (TokenizerEngine.ts:49:22)
    at VR.tokenize (Tokenizer.ts:26:65)
    at wR.tokenize (createParser.ts:23:37)
    at wR.reset (LexerAdapter.ts:18:24)
    at Object.parse (createParser.ts:33:34)
    at tA.parse (Formatter.ts:37:49)
    at tA.format (Formatter.ts:31:22)
    at oA (sqlFormatter.ts:97:57)

**Usage**

- How are you calling / using the library?

- What SQL language(s) does this apply to?
redshift,hive,plsql,singlestoredb,snowflake,spark,transactsql
These dialects have this problem.

- Which SQL Formatter version are you using?
v15.4.6

**Comment by nene** [comment]
This works as designed. Please see the [paramTypes](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/paramTypes.md) config option.

**Comment by meiMingle** [comment]
@nene Great, thanks for your reply. Also I want to ask if there is an option to process only params without formatting, I know it's weird but it's really important to me

**Comment by nene** [comment]
No. There's no way to turn off the formatting part.
