### ISSUE TITLE
[FORMATTING] tsql: char datatype is emitted in uppercase when functionCase is specified as upper

### ISSUE THREAD

**Issue by rmja** [sql-formatter-org/sql-formatter#811]
**Input data**

I run with the option `functionCase: "upper"` and `dataTypeCase: "lower"`.

```tsql
CREATE TABLE Test123(
    Col1 Nvarchar(100),
    Col2 Char(100)
)
```

**Expected Output**

```tsql
CREATE TABLE Test123(
    Col1 nvarchar(100),
    Col2 char(100)
)
```

**Actual Output**

```tsql
CREATE TABLE Test123(
    Col1 nvarchar(100),
    Col2 CHAR(100)
)
```

**Usage**

- How are you calling / using the library? `prettier-plugin-sql`
- What SQL language(s) does this apply to? `tsql`
- Which SQL Formatter version are you using? `15.4.7`

**Comment by nene** [comment]
Thanks for reporting.

Looks like CHAR was mistakenly included in both function and as data type lists. Well, it might be both in Transact-SQL, but SQL Formatter can only handle one.
