### ISSUE TITLE
[FORMATTING] tsql: Some schema or column names follow keywordCase

### ISSUE THREAD

**Issue by rmja** [sql-formatter-org/sql-formatter#812]
When I run with `keywordCase: "upper"`, then it seems to also convert at positions which are clearly e.g. schema name or column name.

**Input data**

```tsql
CREATE TABLE Catalog.Catalog(
    Col1 int,
    Floor int
)
```

**Expected Output**

```sql
CREATE TABLE Catalog.Catalog(
    Col1 int,
    Floor int
)
```

**Actual Output**

```sql
CREATE TABLE CATALOG.Catalog(
    Col1 int,
    FLOOR int
)
```

**Usage**

- How are you calling / using the library? `prettier-plugin-sql`
- What SQL language(s) does this apply to? `tsql`
- Which SQL Formatter version are you using? `15.4.7`

**Comment by nene** [comment]
Thanks for reporting.

Really two separate issues here:

- `table.column` style constructs should never be detected as keywords. This actually works for the column name part, but for some reason I haven't done it for the table name part. Probably these cases don't happen quite as often.
- Function names (like `floor`) should not be detected as keywords. Currently inside the formatter all function names that aren't followed by `(` are treated as keywords. Though I'm not sure why. Must be some reason... Will need to dig deeper.

**Comment by nene** [comment]
Aha... looks like the only reason was that some special functions like `CURRENT_TIME` can be used without parenthesis. Probably better to just treat these as plain keywords or have some special logic for them, as there is really only a limited set of these things.

For now I'll just switch to treating all such function names as plain identifiers, which I think solves more problems than the previous approach.
