### ISSUE TITLE
[FORMATTING] tsql: GO should always be on a separate line

### ISSUE THREAD

**Issue by rmja** [sql-formatter-org/sql-formatter#814]
**Input data**

Which SQL and options did you provide as input?

```tsql
CREATE OR ALTER VIEW Catalog.SomeView
WITH
    SCHEMABINDING AS
SELECT
    t.Id AS TableId
FROM
    Catalog.Table1 t
WHERE
    t.LastModified = 1
GO
CREATE UNIQUE CLUSTERED
INDEX IX_SomeView_TableId ON Catalog.SomeView (TableId);
```

**Expected Output**

```tsql
CREATE OR ALTER VIEW Catalog.SomeView
WITH
    SCHEMABINDING AS
SELECT
    t.Id AS TableId
FROM
    Catalog.Table1 t
WHERE
    t.LastModified = 1
GO

CREATE UNIQUE CLUSTERED
INDEX IX_SomeView_TableId ON Catalog.SomeView (TableId);
```

or something similar. I believe it is reasonable to have `GO` at least on a separate line.
It signals the end of a batch of tsql statements, see https://learn.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-ver16

**Actual Output**

```tsql
CREATE OR ALTER VIEW Catalog.SomeView
WITH
    SCHEMABINDING AS
SELECT
    t.Id AS TableId
FROM
    Catalog.Table1 t
WHERE
    t.LastModified = 1 GO CREATE UNIQUE CLUSTERED
INDEX IX_SomeView_TableId ON Catalog.SomeView (TableId);
```

**Usage**

- How are you calling / using the library? `prettier-plugin-sql`
- What SQL language(s) does this apply to? `tsql`
- Which SQL Formatter version are you using? `15.4.8`

**Comment by nene** [comment]
Thanks for reporting.

It seems that the support of Transact-SQL is really very problematic. Somebody contributed this long-long time ago, and looks like he simply copy-pasted the titles from documentation and declared it as syntax.

I patched this specific bug, but there are countless more like this. If you're really interested in improving the Transact-SQL support, I suggest you take a look at [this list](https://github.com/sql-formatter-org/sql-formatter/blob/master/src/languages/transactsql/transactsql.formatter.ts#L60) and replace it with that contains syntax for starts of actual statements. Like currently it contains:

```
'AGGREGATE',
'APPLICATION ROLE',
```

But instead there should be:

```
'ALTER AGGREGATE',
'DROP AGGREGATE [IF EXISTS]',
'ALTER APPLICATION ROLE',
'CREATE APPLICATION ROLE',
'DROP APPLICATION ROLE',
```
