### ISSUE TITLE
[FORMATTING] Tabulate Alias breaks quoted aliases

### ISSUE THREAD

**Issue by theking2** [sql-formatter-org/sql-formatter#815]
**Input data**

Which SQL and options did you provide as input?

```sql
select
	product.FAMILY_ITEMS_DESCRIPTION `Item family`,
	product.SUBFAMILY_ITEMS_DESCRIPTION `Item subfamily`,
	ITEMNR `Art-Nr.`,
...
```

**Expected Output**

```sql
select
	product.FAMILY_ITEMS_DESCRIPTION                           `Item family`    ,
	product.SUBFAMILY_ITEMS_DESCRIPTION                        `Item subfamily` ,
	ITEMNR                                                     `Art-Nr.`        ,
...
```

**Actual Output**

```sql
select
	product.FAMILY_ITEMS_DESCRIPTION `Item                           family`       ,
	product.SUBFAMILY_ITEMS_DESCRIPTION `Item                        subfamily`    ,
	ITEMNR                                                           `Art-Nr.`     ,
...
```

**Usage**

- Shift+Alt+F
- mariadb
- Prettier SQL VSCode 1.6.0

**Comment by nene** [comment]
Sorry, but I'm going to close this.

If you want to report problems about VSCode Prettier SQL, please use [the special form for reporting issues about that](https://github.com/sql-formatter-org/sql-formatter/issues/new?assignees=&labels=vscode&projects=&template=vscode-prettier-sql.yml&title=Problem+with+outdated+Prettier+SQL+extension).
