### ISSUE TITLE
Feature Request: Support Add Custom KeyWords

### ISSUE THREAD

**Issue by tk-xiong** [sql-formatter-org/sql-formatter#816]
**Describe the Feature**
A clear and concise description of what the feature is.
```
create table if not exists tmp.ads_algo_user_map_play_stats_30d_i_d (
    map_id string comment '地图ID',
    uin bigint comment '用户ID',
    first_play_dt string comment '首次游玩时间',
    last_play_dt string comment '最后游玩时间',
    dt string comment '数据日期'
) comment '地图用户游玩数据统计表' partitioned by (dt string comment '日期分区') stored as parquet location 'obs://tmp.db/xxxxxxxxxxxxxxxxxxx_table_name' tblproperties (
    'parquet.compression' = 'ZSTD',
    'parquet.block.size' = '268435456'
);
```

Desired format:
```
create table if not exists tmp.ads_algo_user_map_play_stats_30d_i_d (
    map_id string comment '地图ID',
    uin bigint comment '用户ID',
    first_play_dt string comment '首次游玩时间',
    last_play_dt string comment '最后游玩时间',
    dt string comment '数据日期'
) comment '地图用户游玩数据统计表'
partitioned by (dt string comment '日期分区')
stored as parquet
location 'obs://tmp.db/xxxxxxxxxxxxxxxxxxx_table_name'
tblproperties (
    'parquet.compression' = 'ZSTD',
    'parquet.block.size' = '268435456'
);
```

**Why do you want this feature?**
Add new lines before the keywords I expect: `location`, `tblproperties`, `stored as`

**Comment by nene** [comment]
This can be achieved by defining [custom dialect](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/dialect.md) which extends [an existing one](https://github.com/sql-formatter-org/sql-formatter/blob/master/src/languages/mysql/mysql.formatter.ts). Something like this:

```js
import { formatDialect, mysql } from 'sql-formatter';

const extraClauses = ['PARTITIONED BY', 'LOCATION', 'TBLPROPERTIES', 'STORED AS'];

const customDialect = {
  ...mysql,
  tokenizerOptions: {
    ...mysql.tokenizerOptions,
    reservedClauses: [...mysql.tokenizerOptions.reservedClauses, ...extraClauses],
  },
  formatOptions: {
    ...mysql.formatOptions,
    onelineClauses: [...mysql.formatOptions.onelineClauses, ...extraClauses],
    tabularOnelineClauses: [
      ...(mysql.formatOptions.tabularOnelineClauses ?? []),
      ...extraClauses,
    ],
  },
};

const result = formatDialect('SELECT * FROM tbl', { dialect: customDialect });
console.log(result);
```

**Comment by tk-xiong** [comment]
How should I enable dialect in VSCode plugin `SQL Formatter VSCode`？

**Comment by tk-xiong** [comment]
I See https://github.com/sql-formatter-org/sql-formatter/issues/580, but it only support pre define dialect.

**Comment by nene** [comment]
Yeah. This won't work in VSCode extension. It also won't work when running `sql-formatter` from command line. The only way to use this feature is when you use SQL Formatter as a library.

However. Why do you even need this kind of feature of custom keywords? I suspect the problem is that SQL Formatter is simply lacking the support for these keywords. I think a better approach in that case would be to just improve MySQL (I guess that's the dialect you're using) support in SQL Formatter, either by sending a bug report or adding these missing keywords to [mysql implementation](https://github.com/sql-formatter-org/sql-formatter/blob/master/src/languages/mysql/mysql.formatter.ts) and sending a pull request.

**Comment by tk-xiong** [comment]
Yes, I asked others, and the dialect I use may be `hive`.
I want to be able to add the following keywords to the [hive implementation](https://github.com/sql-formatter-org/sql-formatter/blob/master/src/languages/hive/hive.formatter.ts):
1. `partitioned by`
2. `stored as` -- it already exists
3. `location`
4. `tblproperties`

But I don't know js development, and I haven't participated in the development and testing of the project.
Can you help add these keywords, or do you expect me to try to develop, test, and then submit PR?
